### ISSUE TITLE
Design decision: Singleton vs per request service

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#10]
Current grpc .NET implementation has a singleton service
ASP.NET Core creates endpoint instances per request, e.g. controllers and service hub

We would prefer per request to support scoped DI scenarios, e.g. DB context

Make a design decision.

**Comment by chwarr** [comment]
FWIW, in my gRPC projects that use the `Microsoft.DependencyInjection` package, I have a server-side call interceptor that starts a new scope automatically so simulate per-call scoping using the generated singletons.

**Comment by JunTaoLuo** [comment]
We think defaulting to a Scoped service would provide better experience with existing aspnet components since it's the predominant design pattern in our framework.

For example, EntityFrameworkCore (EFCore), our OR/M for databases, injects a Scoped service, which means the services that use EFCore need to be a Scoped service lest you manually perform all the database operations:

Startup:
```C#
public void ConfigureServices(IServiceCollection services)
{
    ....
    services.AddDbContext<MovieContext>(options =>
         options.UseSqlServer(Configuration.GetConnectionString("MovieContext")));
}
```
Service:
```C#
class MovieService: Movie.MovieBase
{
    private MovieContext _context;

    // MovieContext is a Scoped service and can only be resolved from the DI if MovieService is not a Singleton service
    public MovieService(MovieContext movieContext)
    {
        _context= movieContext();
    }

    public override Task<MovieReply> GetMoviesCount(MovieRequest request, ServerCallContext context)
    {
        var movies = from m in _context.Movie
                 select m
                 where m.Title.Contains(request.SearchString);
        return Task.FromResult(new MoviesReply { Count = movies.Count });
    }
}
```

There are other examples of components like EFCore that rely on the Scoped service pattern and restricting GRPC services to Singletons would degrade the integration experience with other aspnet components. This is also one of the main reasons why MVC controllers and SignalR Hubs are built with this pattern.

However, for back compatibility, we can make use of the [ServiceActivator pattern](https://github.com/JunTaoLuo/GrpcSandbox/blob/105f2bc65ad1b6b642a62bec31789315936c78b2/Server/Dotnet/DefaultGrpcServiceActivator.cs) to allow the user to explicitly specify a Singleton GRPC service. This would limit the functionality since Scoped services cannot be resolved allows an escape hatch in case the user needs this behaviour

Scoped Service (Default):
```C#
        public void Configure(IApplicationBuilder app)
        {
            app.UseRouting(builder =>
            {
                builder.MapGrpcService<MovieService>();
            });
        }
```

Singleton Service:
```C#
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddGrpc();
            services.AddSingleton<MovieService>(); // This MovieService would not have access to MovieContext
        }
```

**Comment by JunTaoLuo** [comment]
@rynowak wrote another doc on this as well at https://gist.github.com/rynowak/ad96169f045353add6fb3f324107e671

cc @jtattermusch

**Comment by JunTaoLuo** [comment]
I think we have coalesced around the proposed design.
