### ISSUE TITLE
GRPC-Client support for .NET 4.0 and .NET 2.0 (full framework)

### ISSUE THREAD

**Issue by ststeiger** [grpc/grpc-dotnet#1032]
Cool, now we can re-write our dwg-to-svg service from .NET 4.0 WCF to .NET Core grpc. 
And then we can**not** use grpc in the web-application, because there's no client library for .NET 4.0 and 2.0, and we also can't port to .NET Core because there's no WebForms support for VisualBasic.NET ASP.NET WebForms, and we can't port to newer frameworks, because they are not installed on the production servers which run at our clients server parks.

**Comment by JamesNK** [comment]
grpc-dotnet uses HTTP/2. That means it requires .NET Core 3 or later.

If you want a gRPC library that supports .NET Framework then you must use Grpc.Core.

**Comment by ststeiger** [comment]
Why is it called Grpc.Core when it's full framework ? 
That's puzzling, but oh well...
Well ok, upgrading to .Net4.5/4.8 might still be possible.

**Comment by chwarr** [comment]
The C# package "Grpc.Core" is named that way because it exposes C# APIs over the ["gRPC C Core" library](https://github.com/grpc/grpc#about-this-repository). Both gRPC C Core and .NET Core started around the same time as each other (November 2014). I suspect neither was aware of the other when the names were chosen.
