### ISSUE TITLE
Fire and forget support

### ISSUE THREAD

**Issue by manishtiwari25** [grpc/grpc-dotnet#1084]
I just convinced my colleagues to use gRPC instead of the queue for microservice communication but there are some areas in our projects where we need Fire and forget kind of thing, so my question is does gRPC supports fire and forget In .Net Core?

**Comment by JunTaoLuo** [comment]
What do you mean by fire and forget? 

I assume you mean to start a gRPC call and ignore the response? If so you can already do that since clients can terminate early regardless of the server behaviour. However, it's usually better practice for the calls to be designed so that the server returns an empty response, does that not work in your scenario?

**Comment by manishtiwari25** [comment]
Yes, I don't want to wait for the reponse, right now we are using messaging queue to send data to other service and that service is  processing the data and putting it in Db. This is I want to achieve using gRPC, is it possible?

**Comment by JamesNK** [comment]
Sure. Make a call and don't await the response.

**Comment by manishtiwari25** [comment]
Okay, I will try to do that and comment here if I face any issues.

**Comment by LucaMaurelliC** [comment]
@JamesNK How can I make a call without waiting for its response? In my use case I have a PoolThreadExecutor sending requests concurrently and they need to be "fire and forget" because the server receives these requests and start a long computation. The desidered state would be "the server receive the request and its context, return immediatly and then start the computation". How can I achive that?

**Comment by vi12** [comment]
> @JamesNK How can I make a call without waiting for its response? In my use case I have a PoolThreadExecutor sending requests concurrently and they need to be "fire and forget" because the server receives these requests and start a long computation. The desidered state would be "the server receive the request and its context, return immediatly and then start the computation". How can I achive that?

You would have a 2 step process.

1 - Send all the data that needs processing to the Server. The Server responds back, after receiving the data with an answer like "GotTheDataBye"

2 - Server starts processing. On completion, a grpc client on the Server initiates a communication to whoever sent the data for processing, and sends them the results of processing.
