### ISSUE TITLE
Unimplemented service/method

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#109]
## [unimplemented_method](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#unimplemented_method)

Imagine we have a service located at "Count.Counter". It has a method AccumulateCount method at "Count.Counter/AccumulateCount".

Attempting to call a method that doesn't exist on the service, e.g. "Count.Counter/DoNotExist" would return a UNIMPLEMENTED status.

I think we could do this via a policy matcher.

Count.Counter/AccumulateCount -> explicit endpoint
Count.Counter/* -> wildcard endpoint that returns UNIMPLEMENTED status for method

---

## [unimplemented_service](https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md#unimplemented_service)

Imagine we have a service located at "Count.Counter". Someone typos and tries to call "Count.CounterTypo". It should return an UNIMPLEMENTED status.

Doing this is more tricky because Grpc.AspNetCore.Server isn't necessarily the only framework in the web application. We don't want to completely take over request handling and assume that requests that don't match a service should always return a gRPC UNIMPLEMENTED status.

Would returning this status when the URL starts with the package name be enough to meet this requirement? e.g.

Count.Counter/AccumulateCount -> explicit endpoint
Count.Counter/* -> wildcard endpoint that returns UNIMPLEMENTED status for method
Count.* -> wildcard endpoint that returns UNIMPLEMENTED status for service

**Comment by JamesNK** [comment]
@jtattermusch

**Comment by jtattermusch** [comment]
Related to unimplemented_method and unimplemented_service in this issue https://github.com/grpc/grpc-dotnet/issues/32. Interop test descriptions https://github.com/grpc/grpc/blob/master/doc/interop-test-descriptions.md

**Comment by jtattermusch** [comment]
**unimplemented_method** case seems to be relatively straightforward:
whatever URL starts with "/SERVICE_NAME/" where service_name is a gRPC service registered through MapGrpcService, we should have a fallback method handler that returns StatusCode.Unimplemented if a method doesn't exist. I think it's safe to do because registering a gRPC service is equivalent with reserving a whole "directory"  on the http server and it matches with that I'd expect as a user.

**unimplemented_service** case is trickier. You're right that the Grpc.AspNetCore.Server should not claim all the URLs (in fact the ability to server both gRPC and regular HTTP traffic easily is one of the strengths of ASP.NET core compared to other gRPC implementation, where plain HTTP handlers are harder to do). But just assuming that whatever url matches part of protobuf namespace would be treated as gRPC request is also wrong IMHO. Ideas:
- I think it's hard predict what user will want. Should we just provide users with a way to configure the fallback handler and let them decide what they need? (sth. like `routes.MapGrpcUnimplementedHandler(routePrefix)` - a similar pattern could be also used for exposing a "generic" handler that would serve all the request dynamically as if they were a bidi streaming call - the e.g. `routes.MapGrpcGenericHandler(routePrefix)`)
- could we recognize the grpc traffic based on request header and only use the unimplemented fallback if the request is grpc?
- we could configure the behavior in the global GrpcServiceOptions provided in services.AddGrpc(options).

**Comment by JamesNK** [comment]
> * `routes.MapGrpcUnimplementedHandler(routePrefix)`

Yeah we could do that. It would be nice to find a design that doesn't require the user to think about it.

> * could we recognize the grpc traffic based on request header and only use the unimplemented fallback if the request is grpc?

That's an interesting idea. We could return an unimplemented status for any unmatching requests that have a `application/grpc (+proto/+json)` content-type. I didn't think of it because we don't check the request header for any other requests. Should we be validating that header before processing valid service URLs as gPRC?

**Comment by dhhoang** [comment]
FYI, `grpc-java` checks for `application/grpc` content type and returns 415 if invalid (that includes the case where `Content-Type` is not present): https://github.com/grpc/grpc-java/blob/dd466039b52150ef9f7c69ff1c2c611ab1c61c49/netty/src/main/java/io/grpc/netty/NettyServerHandler.java#L403  

Question is should this header be made explicit to Grpc calls.

**Comment by JamesNK** [comment]
If other servers are doing it then so should we. It is useful to check to make to see whether we support the message format used by the request

https://github.com/grpc/grpc-dotnet/pull/122

**Comment by jtattermusch** [comment]
Not sure what would be the overhead of checking the content-type for each request (including non-grpc requests), but if that's not a performance problem, I think a natural solution for the unimplemented_service  case would be to have a default fallback handler for all grpc requests (that match application/grpc or application/grpc+whatever) that would return Unimplemented if the URL is not mapped to a grpc service.  Traffic with other content types would be ignored by this route, so there would be no surprises in terms of interference with other routes setup by the user.
