### ISSUE TITLE
Docs: Unit test gRPC services and clients

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#1128]

**Comment by cwe1ss** [comment]
Looking forward to your take on this! 

Just some input:

I've been struggling a little bit with setting up mocks for clients as gRPC returns `AsyncUnaryCall<>`-objects with its own GetAwaiter-method instead of regular `Task<>`-objects.

I then found `Grpc.Core.Testing` and the following code from [gRPC's MathClientMockableTest.cs](https://github.com/grpc/grpc/blob/a985978d82ef630120b3a93e4fe99069dd5dd4e4/src/csharp/Grpc.Examples.Tests/MathClientMockableTest.cs#L59) as a base:

```csharp
var mockClient = new Moq.Mock<Math.MathClient>();

// Use a factory method provided by Grpc.Core.Testing.TestCalls to create an instance of a call.
var fakeCall = TestCalls.AsyncUnaryCall<DivReply>(Task.FromResult(new DivReply()), Task.FromResult(new Metadata()), () => Status.DefaultSuccess, () => new Metadata(), () => { });
mockClient.Setup(m => m.DivAsync(Moq.It.IsAny<DivArgs>(), null, null, CancellationToken.None)).Returns(fakeCall);
Assert.AreSame(fakeCall, mockClient.Object.DivAsync(new DivArgs()));
```

As that's quite verbose and as we use `NSubstitute` instead of `Moq` in our system, I'm using a custom extension method:

```csharp
public static ConfiguredCall Returns<TResponse>(this AsyncUnaryCall<TResponse> value, TResponse response)
    where TResponse : class
{
    var call = TestCalls.AsyncUnaryCall(Task.FromResult(response), Task.FromResult(new Metadata()), () => Status.DefaultSuccess, () => new Metadata(), () => { });

    return value.Returns(call); // .Returns() is from NSubstitute
}
```
This allows me to set up an expected return-object in a test via something like:

```csharp
MerchantsClient
    .GetMerchantAsync(new GetMerchantQuery
    {
        MerchantId = "id-1"
    })
    .Returns(new Merchant
    {
        MerchantId = "id-1",
        CountryCode = "DE"
    });
```

This works well with one caveat: 

If my tested code does NOT match this expected call, I'm receiving a `NullReferenceException` from NSubstitute as it seems to just return a `null` AsyncUnaryResult<T> and the await call will fail.

The exception points to the location of the failed call in the stack trace, but I have no idea what the actual parameters were, so it would be nice to get something like a `No return-object has been set up matching a call to "GetMerchantAsync({ MerchantId = 'id-1' }"` error instead.

That's obviously more related to NSubstitute, but maybe this is useful for your docs and maybe you have some experience/ideas on how to do that better with NSubstitute or any other testing framework.

PS: Thank you for your work on this library. I finally managed to migrate many of our services to grpc-dotnet and I'm loving it so far!

**Comment by Dannieib** [comment]
Have you tried WireMock package?

I can be of help if you need any. You can reach thru to me on danielibanga4321@outlook.com

With wiremock, you can run test for your logic/services seamlessly...

**Comment by ehsanrezaee** [comment]
You did not copy the code correctly from  [https://github.com/grpc/grpc/blob/a985978d82ef630120b3a93e4fe99069dd5dd4e4/src/csharp/Grpc.Examples.Tests/MathClientMockableTest.cs#L59](gRPC's MathClientMockableTest.cs)
Check again.

**Comment by JamesNK** [comment]
Include docs on how to unit test HttpContext accessed via GetHttpContext() extension method.

**Comment by JamesNK** [comment]
Fixed by https://github.com/dotnet/AspNetCore.Docs/pull/24467

**Comment by Eagle3386** [comment]
@cwe1ss Sorry for the very late revival of this, but your hint:

> As that's quite verbose and as we use `NSubstitute` instead of `Moq` in our system, I'm using a custom extension method:
> ```cs
> public static ConfiguredCall Returns<TResponse>(this AsyncUnaryCall<TResponse> value, TResponse response)
>     where TResponse : class
> {
>     var call = TestCalls.AsyncUnaryCall(Task.FromResult(response), Task.FromResult(new Metadata()),
>                    () => Status.DefaultSuccess, () => new Metadata(), () => { });
> 
>     return value.Returns(call); // .Returns() is from NSubstitute
> }
> ```

Doesn't work for me, no matter how hard I try - first, I always got the error:
`'ConfiguredCall' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'ConfiguredCall' could be found (are you missing a using directive or an assembly reference?)`

I then found out that the code of your extension method wasn't used until I changed its signature from originally
```csharp
public static ConfiguredCall Returns<TResponse>(this AsyncUnaryCall<TResponse> call, TResponse response)
```
to
```csharp
public static ConfiguredCall Returns<TResponse>(this Task<TResponse> value, TResponse response)
```
because my gRPC service's `SendAll` method got generated as returning `Task<ItemsReply>`:
```csharp
var service = Substitute.For<ItemService>(Substitute.For<ILogger<ItemService>>());
var reply = await service.SendAll(Substitute.For<Empty>(), Substitute.For<ServerCallContext>())
// (...)
```

But then I get 2 errors:
- in my unit test (due to my `Returns()` extension method returning `ConfiguredCall` instead of something like `Task<>`):
`'ConfiguredCall' does not contain a definition for 'GetAwaiter' and no accessible extension method 'GetAwaiter' accepting a first argument of type 'ConfiguredCall' could be found (are you missing a using directive or an assembly reference?)`

- in my extension method:
`The type arguments for method 'NSubstituteExtensions.Returns<TResponse>(Task<TResponse>, TResponse)' cannot be inferred from the usage. Try specifying the type arguments explicitly.`
due to my method's body remaining the same as in your example above.

Please, can you help me figure out what's missing/wrong?
Because I want to stick with NSubstitute instead of Moq as JamesNK did in the MS Docs tutorial…

**Comment by idormenco** [comment]
> 

@Eagle3386 I have no idea how @cwe1ss managed to implement that method but I have this solution

```
    public static ConfiguredCall Returns<TResponse>(this AsyncUnaryCall<TResponse> value, TResponse response)
        where TResponse : class
    {
        var call = new AsyncUnaryCall<TResponse>(Task.FromResult(response), Task.FromResult(new Metadata()), () => Status.DefaultSuccess, () => new Metadata(), () => { });

        return SubstituteExtensions.Returns(value, call); // .Returns() is from NSubstitute
    }
```

**Comment by ThabisaniSibanda** [comment]
This worked for me:

            Mock<AsyncUnaryCall<Response>> callMock = new Mock<AsyncUnaryCall<Response>>();
            callMock.SetupGet(s => s.ResponseAsync).Returns(Task.FromResult(new Response { T = { } }));
            _client.Setup(s => s.GetResponseAsync(It.IsAny<Request>(), It.IsAny<Metadata>(), It.IsAny<DateTime>(), It.IsAny<CancellationToken>())).Returns(callMock.Object);

**Comment by Eagle3386** [comment]
@ThabisaniSibanda your code uses Moq while we're talking about NSubstitute instead…
