### ISSUE TITLE
any way to get the state in GrpcChannel

### ISSUE THREAD

**Issue by luchunminglu** [grpc/grpc-dotnet#1275]
In grpc C# (core library based) , Channel has a State property, which Gets current connectivity state of this channel.

Any way to get the state in grpc-dotnet

https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/Channel.cs
```

        /// <summary>
        /// Gets current connectivity state of this channel.
        /// After channel has been shutdown, <c>ChannelState.Shutdown</c> will be returned.
        /// </summary>
        public ChannelState State
        {
            get
            {
                return GetConnectivityState(false);
            }
        }
```

**Comment by JamesNK** [comment]
This isn't supported. There are some tentive plans to add support in the future but it is difficult using .NET's built-in HTTP APIs.

**Comment by pardeike** [comment]
Without having looked too deep, I found UpdateState() in regards to load balancing. Where does the state information for that come from and can it be used?

We are developing a cross platform SDK that uses GRPC and would want to publish simple state changes like "connection established" and "connection offline" to our clients. Can you elaborate why the .NET HTTP API does not provide this? I assume you internally have logic to detect state changes indirectly, especially for the retry logic.

**Comment by janseris** [comment]
It's kinda annoying that we cannot check for state in the Grpc.Net.
How can I tell that the server is unreachable at the moment?

I am implementing both .NET 5 (Grpc.Net NuGet package) and .NET Framework (Grpc.Core NuGet package).

In the .NET Framework I can check channel.State.
When I want to tell that the server is unreachable, I check in the RpcException that the status is Unavailable.
If both exception status is Unavailable and channel status is not Ready (either Connecting or TransientFailure), I know that there is something wrong with the connection (either the server is off or it is on but I cannot reach it, e.g. my internet connection has a temporal error).

As far as I have tried, this cannot be detected in .NET 5 implementation (Grpc.Net package). Or is it possible there, too?
It is not nice to use the Unavailable state to check if the server is or on off because the code should be already used for a failure in the services pipeline (maybe a database behind the gRPC server is offline - should Unavailable be used in this case? If yes, then we have to be able to distinguish between server unavailable and service unavailable (unable to process the request).

**Comment by JamesNK** [comment]
This is supported now in the latest preview*. There is a state property and method to subscribe to state changes.

*Only available in previews. Stable versions are skipping this feature until it is properly tested.

**Comment by tank104** [comment]
@JamesNK when you say its supported in Preview - it looks like we need to compile with SUPPORT_LOAD_BALANCING.  Is this kind of a preview compilation tag?  Also has been a year, so just wondering when plans would be to incorporate it into main build?

**Comment by JamesNK** [comment]
`SUPPORT_LOAD_BALANCING` flag is set on platforms that support load balancing, which includes the state property:

https://github.com/grpc/grpc-dotnet/blob/9427a740a468e10c1daa2443061d2d1609bf1777/src/Grpc.Net.Client/Grpc.Net.Client.csproj#L17-L19
