### ISSUE TITLE
"Can't write the message because the previous write is in progress." during streaming

### ISSUE THREAD

**Issue by datoml** [grpc/grpc-dotnet#1333]
Hello,
I have the problem that the server throws sometimes an InvalidOperationException during streaming with the error message "Can't write the message because the previous write is in progress.".
Based on the source code it seems that the client hasn't received all data yet and a new write will start.

My first idea was to check if a previous write is in progress. But the property that holds the information is private. So I have no chance to check if I am able to write a new message.

Or is this a problem with my code on the server?
The implementation on the server is this one.

```
public override async Task Subscribe(SubscribeRequest request, IServerStreamWriter<SubscribeResponse> responseStream, ServerCallContext context) {
	try {
		async void connectionAction(ConnectionStatusData? connectionStatus) {
			var opts = responseStream.WriteOptions;
			await responseStream.WriteAsync(new SubscribeResponse {
				ConnectionStatus = connectionStatus
			}).ConfigureAwait(false);
		}

		_device.OnConnectionStatusChanged += connectionAction;

		await ThreadHelper.WaitOneAsync(context.CancellationToken.WaitHandle, Timeout.Infinite, CancellationToken.None).ConfigureAwait(false);

		_device.OnConnectionStatusChanged -= connectionAction;
		_logger.LogDebug("Client closed stream.");
	}
	catch (TaskCanceledException ex) {
		_logger.LogWarning(ex, "Streaming task was canceled");
	}
	catch (Exception ex) {
		_logger.LogError(ex, "Unexpected error");
	}
}
```

Thank you in advance!

**Comment by JamesNK** [comment]
The problem is the `async void` in line 3 of your sample. Nothing is stopping an event from being raised and this code executing while a `WriteAsync` is already in progress.

What you could do is create a producer/consumer channel. In `connectionAction` you would add an entry to the channel, and replace WaitOneAsync with a loop that reads from the channel reader.

https://github.com/grpc/grpc/blob/471df710034847bb268e76d91f83279c41fd932a/src/csharp/Grpc.HealthCheck/HealthServiceImpl.cs#L209-L217

Use cancellation token with `WaitToReadAsync`.

**Comment by datoml** [comment]
Thanks for the hint. I had completely overlooked this case.

**Comment by datoml** [comment]
@JamesNK Thank you for your help. The approach with producer/consumer fixed the issue.
Have a nice day!
