### ISSUE TITLE
gRPC “callback” functions calling order

### ISSUE THREAD

**Issue by KamarasV** [grpc/grpc-dotnet#1378]
Hi everyone

As you know gRPC contains unary and streaming functions which are cool but in a modern RPC technology, especially in a microservice environment a library like this need to provide a solution for callback functions where the server can call back the client. I think this is important because we do not want the client to poll the server. In the base ASP.NET this functionality is provided by SignalR and websocets. 

In gRPC the callback functions can be implemented throught streaming functions in a way described in this msdn article:
[Migrate WCF duplex services to gRPC](https://docs.microsoft.com/en-us/dotnet/architecture/grpc-for-wcf-developers/migrate-duplex-services)

and I have to say it is working fine but my problem is the calling order is not guaranteed at client side. 

I mean, in a case of one callback function (streaming function) if I put data into the function in a specified order I got these data at client side in a same order but if I have multiple callback functions implemented in a way described in the article, and call the functions in a specified order at server side like:

**_Functions1
Functions2_**

At client side the incoming calling order will not be necessary the same, so in some cases this can be:

**_Functions2
Functions1_**

**This is very disturbing and make gRPC unusable in some case. I would like to know if there is or will be any solution to this problem because this is the only thing we use SignalR instead of gRPC.**

**Sample code of the implementation of the callback function**

Server side implementation:

```
public override async Task UpdateProgress(Empty request, IServerStreamWriter<PercentageParams> responseStream, ServerCallContext context)
{
    _callbackContainer.UpdateProgress = async (percentage) => await 
    WriteUpdateProgressAsync(responseStream, percentage);

    //One synchronised call is necessaray to make sure the callback is stored before the await returns at client side from the Callback handler class
    WriteUpdateProgressAsync(responseStream, 0).Wait();
    await AwaitCancellation(context.CancellationToken);
}

private async Task WriteUpdateProgressAsync(IServerStreamWriter<PercentageParams> stream, uint percentage)
{
    try
    {
        await stream.WriteAsync(new PercentageParams 
        {
            Percentage = percentage
        });
    }
    catch (Exception e)
    {
        _logger?.LogError($"Failed to write message: { e.Message }");
    }
}
```

**Client side implementation:**

```
public async Task UpdateProgressHandler()
{
     using (var serverStream = _client.UpdateProgress(new ConverterProcess.Empty()))
     {
            await BuildUpConnectionAndWaitForTheResponse(serverStream, () =>
            {
                Console.WriteLine($"Conversion state: {serverStream.ResponseStream.Current.Percentage}");
            });
     }
}

private async Task BuildUpConnectionAndWaitForTheResponse<ResultType>(Grpc.Core.AsyncServerStreamingCall<ResultType> serverStream, Action todo)
{
        //One synchronised call is necessaray to make sure the callback is stored before the await returns 
        serverStream.ResponseStream.MoveNext(_cancellationTokenSource.Token).Wait();

        while (await serverStream.ResponseStream.MoveNext(_cancellationTokenSource.Token).ConfigureAwait(false))
        {
            todo?.Invoke();
        }
}
```

The client first calls the "UpdateProgress" function at server side. The call creates a lambda function which will be the callback and can be called from enywhere until the "UpdateProgress" is cancelled with a cancellation token. If the lambda is called at server side the call end up at client side in the while function.

This is one callback function and works fine. The problem comes if you have two (the second can be for example "UpdateStatus") and want to call them in turn:

UpdateProgress UpdateStatus UpdateProgress UpdateStatus

At client side the order will bi different.

Thanks
Viktor Kamarás

**Comment by jtattermusch** [comment]
gRPC's approach for server notifying the client about something is using the server-streaming mechanism (as you already know). The order of messages in the server-side stream is always preserved, but only for a given RPC.  If you have multiple parallel RPCs that send a server-streaming message at the same time, there is not guarantee about the order they will be delivered to the client, which is something that's working as intended (as those are two completely independent HTTP/2 streams and they basically behave as if you had 2 completely separate pipes that deliver data).
If you want to guarantee the ordering of response messages in all cases (because you application logic relies on that), simply make sure that you received all the interdependent updates through a single RPC - basically what you want is to have an RPC with multiple possible response types (e.g. use a protobuf "oneof" field for the reponse type) and send all the updates for which you need ordering guarantees though this single RPC. I don't know the details of your applications, but having a single server-streaming RPC that returns both UpdateProgress and UpdateStatus responses in a single stream seems to make sense.
