### ISSUE TITLE
Add IAsyncStreamWriter<T>.WriteAsync(T, CancellationToken) overload

### ISSUE THREAD

**Issue by tommyja** [grpc/grpc-dotnet#1422]
### Problem

There is no way for the server to discover that a client is not consuming a stream.
For a long lived stream, this can lead to WriteAsync eventually blocking forever on the server side.

### Possible solution

Add a timeout option to IAsyncStreamWriter.WriteAsync 
If the message is not sent to the client within the timeout, terminate the stream or call a provided Action

### Workarounds considered

1. Start a timer when WriteAsync is called. If the timer triggers before WriteAsync  returns, terminate the stream. The problem with this is that WriteAsync does not block before the out buffer is full. This can take a long time for low throughput streams.

2. Using bidirectional streams with sequence number in the proto . Terminate stream if ack for a given sequence number is not received within the timeout. This works but is clumsy.

**Comment by davidfowl** [comment]
@jtattermusch WriteAsync needs a CancellationToken. That's a breaking change though so we'll need to figure something out.

**Comment by tommyja** [comment]
@davidfowl a cancellation token would help in many cases, but it will not solve the case with low volume streams as it can take a long time to fill the out buffer,

**Comment by JamesNK** [comment]
The only way I could imagine this working is if there was a way to monitor flow control's window size - https://medium.com/coderscorner/http-2-flow-control-77e54f7fd518

As the server writes more data to the client, the available buffer space on the client decreases. When the client reads the incoming messages then it reports back that it has buffer space.

As far as I know, there is no API to notifications about flow control size changing in Kestrel. Correct me if I'm wrong @davidfowl.

Having the client report receipt of messages using a bidirectional stream will certainly work.

**Comment by jtattermusch** [comment]
What exactly is the kind of scenarios you'd like to be able to detect?
- if connection is broken (or other fatal problem happens), the entire RPC is going to be cancelled and all the methods like WriteAsync are going to return immediately (which AFAIK is the current behavior).
- if the client is just reading slowly, it's basically impossible to detect whether the connection is just slow, client is processing data slowly or if client is stuck, so I don't know what value there is in "discovering that client is not consuming a stream". If you need to guarantee that the client has seen the data you've sent, on time, you need to use the approach described in workaround 2 ("explicit confirmations").

Btw, the API is designed so that you can cancel an RPC anytime (on server or on client), which causes all the async in flight operations for a given RPC (e.g. a read, a write, etc.) to fail. If you feel like the peer on the client side has gotten stuck (which is going to be difficult to detect, and it's going to always be just a guess basically), you can always cancel the entire RPC by cancelling the ServerCallContext.CancellationToken.  Cancelling operations on an RPC separately makes no sense (as if one of them fails, all of them will fail).
https://github.com/grpc/grpc/blob/ee5a6851111a882003e76123fb137f176fb9c839/src/csharp/Grpc.Core.Api/ServerCallContext.cs#L76

WriteAsync is supposed to start blocking once the flow control window is full (so that the API can convey the fact that the flow control window is full and the user code can detect this condition).

**Comment by jtattermusch** [comment]
> So there will be no way for service applications to take advantage of the underlying flow control and push back on their clients in stead of implementing a custom flow control mechanism.

The way the flow control push back is implemented in C# (and in most other gRPC implementations out there) is that the write operation doesn't succeed/return (in the async/await sense in C#'s case) until the write has passed flow control. So if the peer stops reading the messages (e.g. in a streaming call), eventually the flow control window will become full and the write operations will start to "block" for the sender (again, "block" is meant in the async/await sense).  That's a simple and straightforward way of ensuring that the readers can push back on the writers and it doesn't require exposing extra complicated knobs in the API to work (and that also makes sure that the flow control does the right thing for everyone by default).

**Comment by jtattermusch** [comment]
> @JamesNK, I don't understand how this can be closed, at the very least it needs to take a cancellation token. If the write async blocks, the stream will never complete and there is no good way for the server to cancel it. The workaround for now is something like (clunky and wasteful): await Task.WhenAny(responseStream.WriteAsync(response), Task.Delay(5000).ContinueWith((_) => throw new TaskCanceledException("timeout on write to response stream"))));
> 
> If WriteAsync had an overload with a cancellation token or an overload that would return immediately with an error if the out buffer is full, it would at least be a lot better.
> 
> e.g: using var cts = new CancellationTokenSource(); cts.CancelAfter(5000); responseStream.WriteAsync(response, cts.Token;)
> 
> Another and better option would be to add timeout or "fail on buffer full" to the WriteOptions
> 
> e.g. responseStream.WriteOptions = new WriteOptions(timeout = 5000) responseStream.WriteOptions = new WriteOptions(failonBufferFull = true)
> 
> @jtattermusch
> 
> Just to clarify what I mean with "client is not consuming a stream": I mean that it stops calling call.ResponseStream.MoveNext without disposing the call for whatever reason.
> 
> My particular problem is with long lived streams with very low activity. If the client gets stuck and stops consuming, it can hold on to the stream for a very long time with no way for the server to detect this and cancel the stream. The server will eventually run out of resources if this happens on multiple streams. This can happen if there is a bug in the client or if the client is trying to forward the data to some other service that is for some reason is pushing back. Its not due to the connection, other streams to the same client may be functioning as normal.

Would setting a timeout for the entire call help you? Setting some timeout is a good practice even for streaming calls. Also, whenever you are using streaming, you usually need to have a mechanism to recreate the streaming call if it fails (e.g. network problems, TCP stream killed due to inactivity etc.), so if your clients set some reasonable timeout for the RPC calls they start, the streaming calls will get cleaned-up automatically after a while.

(FTR some useful tips on streaming calls are here: https://www.youtube.com/watch?v=Naonb2XD_2Q)
> 
> Yes, the server can cancel the stream if this situation is detected. But since await WriteAsync will just wait forever, its hard to detect, even with a high activity stream.

I'm not convinced that detecting of how long WriteAsync is taking is a useful general mechanism for detecting that the peer has stopped reading, but if it works in your use case, detecting whether the last write on given RPC has been taking too long is easy - just reset a timer every time you start a WriteAsync (there can only be one WriteAsync for given call at a time) and if the WriteAsync has been taking excessively long (looks like you know the right latency for your use case) just terminate the server-side handler and the call will stop (and server-side resources will be released).

> 
> BTW how do you cancel ServerCallContext.CancellationToken from the server side?

My bad, you cannot trigger a cancellation with `ServerCallContext.CancellationToken`. But simply returning from your server-side handler (or throwing) should be enough to finish the call (with a non-ok  status code, if what you intend to do is to "cancel" the call). So regardless of what is the detection mechanism for detecting the "call has stalled and needs to be terminated", you can terminate the call on the serverside.
> 
> You write "If you feel like the peer on the client side has gotten stuck (which is going to be difficult to detect, and it's going to always be just a guess basically)" I dont understand this. If the client stops sending WINDOW_UPDATE (which is per stream as far as I understand), the server knows that the client has stopped consuming the stream, its just not exposed on the grpc API. Cancelling the stream after a timeout would make sense. or what am I missing?

**Comment by JamesNK** [comment]
Blocked on https://github.com/grpc/grpc/pull/27886
