### ISSUE TITLE
Handling case where unary call contains a status of OK on success

### ISSUE THREAD

**Issue by leonardder** [grpc/grpc-dotnet#1922]
I'm trying to host several GRPC services under IIS that are load balanced using Citrix ADC. Somehow, Citrix ADC adds a grpc status header with code 0 (OK) to succesful unary calls. According to the following snippet, this is not allowed:
https://github.com/grpc/grpc-dotnet/blob/45dd5d171c2ffe446a7c30d4d7b849db3c297bbe/src/Grpc.Net.Client/Internal/GrpcCall.cs?plain=1#L514-L525
And indeed, I'm getting an exception with a message of ""Failed to deserialize response message" when doing an unary call. The same call doesn't fail whenusing postman.

1. Is this check for status = 0 still appropriate?
2. Shouldn't the status have a more descriptive message of what's actually happening, e.g. "The server returned a status code unexpectedly"?

**Comment by JamesNK** [comment]
Returning `grpc-status` in the header isn't unexpected. It indicates a trailers-only response. See https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md#responses

A response with a `grpc-status` header of 0 (OK) doesn't make sense. Because there is no message sent in a trailers-only response, there is no way it could be 0 (OK) because there is no message to deserialize.

**Comment by leonardder** [comment]
Thanks for pointing this out. Looks like there is definitely somethign wrong in the ADC then.
Regardless, would it be possible to change the status message into something more descriptive? I find "Failed to deserialize response message" still a bit confusing in this case.

**Comment by JamesNK** [comment]
Done: https://github.com/grpc/grpc-dotnet/pull/1931

**Comment by leonardder** [comment]
Thanks a lot!
