### ISSUE TITLE
Large binary data transfer

### ISSUE THREAD

**Issue by zs-dima** [grpc/grpc-dotnet#1944]
Could be nice to optimize large binary data transfer with gRPC.
Currently gRPC serialize / de-serialize even binary data messages, so it taking 2 to 3 times more to transfer data with gRPC.
Could be nice to improve protocol to mark some data to be transferred whiteout serialization.

Some more related information about:
https://github.com/grpc/grpc-dotnet/issues/1186
https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-7.0

**Comment by JamesNK** [comment]
What exactly do you mean?

The reason guidance says to use something else is because gRPC is message based. It will never be as efficient as streaming over an HTTP request or response body.

You could choose not to use Protobuf (this is possible today), and have gRPC send and receive byte arrays, but it's still materialized messages with that associated overhead.

**Comment by zs-dima** [comment]
@JamesNK the Idea to use certain service to solve certain task instead to split service without any need into two services.
So if some messages contains big data and non-big data could be nice to mark this data to transfer them efficiently.
Sure it is possible reinvent the wheel and create 2 services from one, duplicate some code and arrange this services communication if needed. 
But optimizing gRPC looks better solution.

**Comment by JamesNK** [comment]
It would be nice if a car could also fly, but there are technical realities:

> The reason guidance says to use something else is because gRPC is message based. It will never be as efficient as streaming over an HTTP request or response body.
