### ISSUE TITLE
Inconsistent behavior of WriteAsync in IClientStreamWriter

### ISSUE THREAD

**Issue by Gawel-Szymanski** [grpc/grpc-dotnet#1995]
### What version of gRPC and what language are you using?
C#, Grpc.Net 2.40

### What did you do?
If possible, provide a recipe for reproducing the error. Try being specific and include code snippets if helpful.
Scenario 1# first WriteAsync is blocked:
1) Create a proto service definition like so: 
`service ChatService {  rpc SendMessages (stream OutgoingMessage) returns (Acknowledgement); }`
2) Create a client and call `var call = client.SendMessages();`
3) Obtain a request stream from a call `var stream = call.RequestStream;`
4) Disable outgoing connections for client application, can be done using Windows Defender Firewall
5) Call `await stream.WriteAsync(message);`
6) The WriteAsync method finishes without issues event though there is no message sent to the server
7) When observing the call object through `await call;` we get an RpcException outside of context of method calling WriteAsync

Scenario 2# second WriteAsync is blocked
1) Create a proto service definition like so: 
`service ChatService {  rpc SendMessages (stream OutgoingMessage) returns (Acknowledgement); }`
2) Create a client and call `var call = client.SendMessages();`
3) Obtain a request stream from a call `var stream = call.RequestStream;`
4) Call `await stream.WriteAsync(message);`
5) Disable outgoing connections for client application, can be done using Windows Defender Firewall
6) Call `await stream.WriteAsync(message);`
7) The WriteAsync method fails with an exception 
### What did you expect to see?
I'd expect to see an exception at every call to WriteAsync that failed to write to a stream, like in Scenario #2, having this error thrown outside of WriteAsync makes it very unwieldy to handle by clients of my service.

### What did you see instead?
When first call is made without internet connection the WriteAsync method does not fail instead we get an error on different thread directly from `call` object if the first WriteAsync is succesful the next WriteAsync will behave properly and return an exception directly to the caller.
Make sure you include information that can help us debug (full error message, exception listing, stack trace, logs).

**Comment by JamesNK** [comment]
I don't believe it's possible to get consistent behavior here. If the HTTP client thinks the connection and request are healthy, then the message data is sent off to the socket and the `WriteAsync` task is marked as complete. I'm guessing that is done for performance reasons. The HTTP client doesn't wait to verify the data is successfully received by the server.

The error is noticed by the code waiting for a response because the connection/request reports it is unhealthy after a previous `WriteAsync` call failed. Additional `WriteAsync` calls would also fail, but you'll probably see the failure waiting for the response first.

I think if you want to verify that the peer has received the message, the foolproof way to do that is for the peer to stream an acknowledgment message back. e.g.

`service ChatService {  rpc SendMessages (stream OutgoingMessage) returns (stream Acknowledgement); }`

**Comment by Gawel-Szymanski** [comment]
Hey @JamesNK thanks for the reply, I don't think you are correct though, "The error is noticed by the code waiting for a response because the connection/request reports it is unhealthy after a previous WriteAsync call failed. Additional WriteAsync calls would also fail, but you'll probably see the failure waiting for the response first." This is not true since there is no "previous WriteAsync" in Scenario 1#. The first call ever fails because of blocked internet connection and never throws an exception. What I'm expecting is that the first WriteAsync will fail  with exception the same way as any other.

**Comment by JamesNK** [comment]
I talked with more people, and the consensus is any sockets-based client will have this kind of problem. Write operations don't wait until they receive an acknowledgment from the server that data is received.

As I said before:

> I think if you want to verify that the peer has received the message, the foolproof way to do that is for the peer to stream an acknowledgment message back. e.g.
> 
> `service ChatService { rpc SendMessages (stream OutgoingMessage) returns (stream Acknowledgement); }`
