### ISSUE TITLE
Instantiation of ServerCallContext shouldn't require Grpc.Core.Testing nuget

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#2]
asp.net core integration will need to create instances of ServerCallContext that will be passed to server-side method implementations,but the constructor is internal-only. Currently instantiating requires Grpc.Core.Testing nuget, which is fine as a workaround, but shouldn't be required in the future.

**Comment by jtattermusch** [comment]
CC @JunTaoLuo

**Comment by JunTaoLuo** [comment]
Will we need to have ServerCallContext exposed? From the samples I've been working on, I expect to use `HttpContext` instead of `ServerCallContext`. I think some of the fields will likely not be relevant such as the `CallSafeHandle`, though I'm not sure about the others. We should look at each of the fields defined on the `ServerCallContext`, determine how they are used and whether they are relevant in the dotnet implementation.

**Comment by jtattermusch** [comment]
We will need to pass in instance of ServerCallContext  to the server-side method implementations:
https://github.com/grpc/grpc/blob/7ef8fc826c52b0c4abeaead633d464197fc0bdf8/examples/csharp/Helloworld/GreeterServer/Program.cs#L27

the context provides access to request/response metadata and and a few other rather important things. Most of them make sense to be populated in the pure C# impl too.
https://github.com/grpc/grpc/blob/master/src/csharp/Grpc.Core/ServerCallContext.cs

**Comment by JunTaoLuo** [comment]
Actually, that's fair, it's a good idea to keep the same API surface so implementers can move between the two servers without needing to rewrite anything.

**Comment by JunTaoLuo** [comment]
I think this is addressed by https://github.com/grpc/grpc/pull/17733. @jtattermusch is there any more work required for this item or can we close this as done?
