### ISSUE TITLE
Document Grpc.Tools and Alpine

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#2048]
Grpc.Tools doesn't work on Alpine - https://github.com/grpc/grpc/issues/18338. It doesn't look like there is a real fix in the short term.

There are some workarounds:
* Move Grpc.Tools to another project, publish project to nuget feed, reference nuget package in app.
* Copy generate source and add it to the project, then remove Grpc.Tools.
* Using [sgerrand/alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc) instead of libc6-compat solves all issues with grpc.* nuget packages.

Add workarounds to [gRPC troubleshooting page](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0) to help people who want to use gRPC + Alpine.

**Comment by MrVinkel** [comment]
Hi,

Installing [sgerrand/alpine-pkg-glibc](https://github.com/sgerrand/alpine-pkg-glibc) did not work for me. 

Another workaround is to install protobuf and grpc in alpine and setting `PROTOBUF_PROTOC` and `GRPC_PROTOC_PLUGIN` https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md#environment-variables

This will make msbuild use the protoc and grpc_csharp_plugin in /usr/bin instead of the ones in the nuget package

```bash
apk add protobuf protobuf-dev grpc
PROTOBUF_PROTOC=/usr/bin/protoc
GRPC_PROTOC_PLUGIN=/usr/bin/grpc_csharp_plugin
```

**Comment by tonydnewell** [comment]
A workaround is now documented here:
https://github.com/grpc/grpc/blob/master/src/csharp/BUILD-INTEGRATION.md#using-grpctools-with-unsupported-architectures

**Comment by JamesNK** [comment]
That's great. I'll link to it from https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0
