### ISSUE TITLE
gRPC with Azure Static Web App

### ISSUE THREAD

**Issue by poornimanayar** [grpc/grpc-dotnet#2165]
I am trying to host a Blazor app in Azure SWA and use gRPC Web. But Azure SWA needs /api prefix on the api as a requirement. Is there any way to achieve this in Azure?

**Comment by JamesNK** [comment]
https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0#calling-grpc-services-hosted-in-a-sub-directory

**Comment by poornimanayar** [comment]
Thanks James, but this is for the client right? I am after the server side to prefix /api. I can't do that in Container Apps or Linux web app. Since it's Blazor, it has to be gRPC-Web so I was wondering whether I can host gRPC service on Windows app service? It's not too clear.

**Comment by JamesNK** [comment]
Ok.

Some thoughts:
1. I don't know whether the gRPC-Web client supports a prefix.
2. gRPC-Web CORS needs some configuration. For example, you need to configure the grpc-status and grpc-message headers to be accessable.
3. I don't know if there is a way to force a Grpc.AspNetCore powered server to have a prefix. Maybe `app.Group("/api").MapGrpcService<Foo>()` would work?

**Comment by poornimanayar** [comment]
hi @JamesNK ,

Yes. I can see it is at the prefix for gRPC-client support that it fails. Is it something that we can provide support for? I assume it will need forcing of the request url to pick up the subdirectory as the delegating handler in the documentation [here]( https://github.com/grpc/grpc-dotnet/blob/master/src/Grpc.Net.Client.Web/GrpcWebHandler.cs#L166) ? Or is it more complex than that?

**Comment by JamesNK** [comment]
I'm completely unfamiliar with what you're doing and don't understand based on your descriptions.

* If you have a .NET client that you want to add a prefix to the URL, then use this: https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0#calling-grpc-services-hosted-in-a-sub-directory
* A .NET `Grpc.AspNetCore` server doesn't have the ability to add a prefix. Maybe it might work using `app.Group("/api").MapGrpcService<Foo>()`. I don't know.
* I can't speak for any other client or server implementations.

**Comment by poornimanayar** [comment]
Sorry if I was unclear. When I use gRPC-Web I want to suffix my server url with `/api` just like we have https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0#calling-grpc-services-hosted-in-a-sub-directory. Currently gRPC-Web does not support that. My question is can we bring in a constructor to have the path included when the request is sent? Unless there is another way in gRPC-Web to achieve that?

I tried your suggestion of `app.Group("/api").MapGrpcService<Foo>()` on the server, which works with a Console app and brings in a DelegatingHandler. But not with gRPC-Web unfortunately.

**Comment by JamesNK** [comment]
> Currently gRPC-Web does not support that

I don't know what that means. gRPC-Web is a standard. Are you saying the standard doesn't allow for it? Or are you talking about a certain implementation?

I'm assuming you mean you want to do gRPC-Web with Grpc.Net.Client, and you can't. What exactly doesn't work? Why do you say it's not supported? I need more information about what you've tried and what doesn't work, and what happens when it doesn't work, because I'm struggling to understand what you're talking about in this issue.

I would have thought the [SubdirectoryHandler](https://learn.microsoft.com/en-us/aspnet/core/grpc/troubleshoot?view=aspnetcore-7.0#calling-grpc-services-hosted-in-a-sub-directory) delegating handler could but use together with the [GrpcWebHandler](https://learn.microsoft.com/en-us/aspnet/core/grpc/grpcweb?view=aspnetcore-7.0) delegating handler. They handlers in a pipeline that can be used together. Something like:

```csharp
var channel = GrpcChannel.ForAddress("https://localhost:5001", new GrpcChannelOptions
    {
        HttpHandler = new SubdirectoryHandler(new GrpcWebHandler(new HttpClientHandler()), "/api")
    });

var client = new Greeter.GreeterClient(channel);
var response = await client.SayHelloAsync(new HelloRequest { Name = ".NET" });
```
