### ISSUE TITLE
Support for Kestrel/Dotnetty for non ASP.NET Core(`Microsoft.NET.Sdk`) users 

### ISSUE THREAD

**Issue by Jeevananthan-23** [grpc/grpc-dotnet#2194]
Hi @JamesNK, I need to understand that non-ASP.NET CORE user can use Grpc.Core (http2c) which is currently not supported by grpcdotnet  because ASP.NET CORE is the only focus. But it could be great that grpcdotnet supports Kestrel/Dotnetty which that can be usefully by `Microsoft.NET.Sdk` SDK.  Kindly check out gRPC Java netty implementation. https://github.com/grpc/grpc-java/tree/master/netty/src/main/java/io/grpc/netty

_Originally posted by @Jeevananthan-23 in https://github.com/grpc/grpc-dotnet/issues/2147#issuecomment-1636307590_

**Comment by JamesNK** [comment]
I don't understand what you're asking for here.

`Grpc.AspNetCore` supports Kestrel, Http.sys, and IIS. The community could support other servers, but there is no plan for official support.

**Comment by gsw945** [comment]
@JamesNK 
maybe I understand what @Jeevananthan-23 said:

every c# project has one `*.csproj` file:
- .NET normal project looks like below:
```xml
﻿<Project Sdk="Microsoft.NET.Sdk"></Project>
```
- .NET web project looks like below:
```xml
<Project Sdk="Microsoft.NET.Sdk.Web"></Project>
```

but we must create a web project to use `Kestrel`, because `Kestrel` is inside `Microsoft.NET.Sdk.Web`.
but our project not needed to be a web project, many package in `Microsoft.NET.Sdk.Web` is not needed in our `Microsoft.NET.Sdk` project.

so, we hope `Kestrel` could be an separated package which can be used in `Microsoft.NET.Sdk`  directly.

**Comment by JamesNK** [comment]
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/target-aspnetcore?view=aspnetcore-7.0&tabs=visual-studio#use-the-aspnet-core-shared-framework

**Comment by gsw945** [comment]
According to NuGet:
[Microsoft.AspNetCore.App](https://www.nuget.org/packages/Microsoft.AspNetCore.App) is Deprecated

**Comment by JamesNK** [comment]
`<FrameworkReference Include="Microsoft.AspNetCore.App" />`

✨ ✨ ✨  **_FrameworkReference_** ✨ ✨ ✨

**Comment by gsw945** [comment]
I got it, thank you very much.
