### ISSUE TITLE
For Code-First GRPC, is there any alternative solution of BindService()

### ISSUE THREAD

**Issue by Naganathan** [grpc/grpc-dotnet#2195]
Instead of proto file, I am converting my code to code-first approach of GRPC. 

My case, I am using BindService() to register a service (implemented from proto file) but I can't register service by using code-first apporach.

Is there any alternative solution instead of using BindService() for code-first approach?

`            
server = new GrpcServer
{
Services = { GreeterServer.BindService(GreeterServerService) },  
Ports = { new ServerPort("0.0.0.0", 8090, ServerCredentials.Insecure) }
};
`

**Comment by mgravell** [comment]
Note that a lot of the ugly logic here is hidden in [ServerBinder](https://github.com/protobuf-net/protobuf-net.Grpc/blob/main/src/protobuf-net.Grpc/Configuration/ServerBinder.cs), which deals with a log of things like reflection discovery. However, I should also note that I'm currently investigating switching to "generators" instead of all this reflection, for performance and AOT reasons - i.e. I intend to implement a generator that implements all the thinking, keeping the runtime very simple.

As a final thought: if you're only just setting out, maybe consider just leaning on protobuf-net.Grpc, which already deals with all the code-first gRPC setup for you? It is pretty flexible. Happy to talk on that too!

(to be explicit: I have two different hats: I work in the Microsoft "distributed systems" team which helps here on the official dotnet grpc project; but I'm also the author of protobuf-net/protobuf-net.Grpc which adds code-first scenarios; I can offer help under either hat)

**Comment by Naganathan** [comment]
Hi @mgravell,

Thanks for your valuable update.  

[ServiceModel](https://github.com/max-ieremenko/ServiceModel.Grpc) resolved my issue and Its pretty simple. Probably I thought they are using that you suggested logic in [ServiceModel](https://github.com/max-ieremenko/ServiceModel.Grpc)'s code implementation.

Thanks,
Naganathan

**Comment by mgravell** [comment]
That's two reference implementations linked - closing out.
