### ISSUE TITLE
Proper configuration for many client connections

### ISSUE THREAD

**Issue by SCLDGit** [grpc/grpc-dotnet#2268]
We have a server application that maintains two types of client connections: a GUI application allowing user interaction, and long-running one-way streaming connections to a potentially very large number of autonomous client agent applications (2000 in our testing, up to 20000 in client production environments). In a scenario where a large number of agent clients attempt to connect (large VM deployment) or reconnect (server restart), we are seeing a massive amount of slowdown and a major loss of responsiveness from the server as the clients attempt to perform their connection process, which is a very simple unary service that is implemented like this:

```
public override async Task<G_ConnectCheckResponse> CheckServerConnection(G_ConnectCheckRequest p_request, ServerCallContext p_context)
{ 
    m_logger.LogDebug("Shield/Client at {ClientAddress} checked for server availability", p_context.GetHttpContext().Connection.RemoteIpAddress);
    
    return await Task.FromResult(new G_ConnectCheckResponse());
}
```

When clients begin their connection check, they are each given a random delay between 10 seconds and 3 minutes in order to attempt to prevent exactly what we're seeing. Even with this in place though, we're seeing massive delays when someone using the GUI application attempts to connect or perform operations that require a server response. Based on our logging, agent connection checks do not appear to happen with any level of concurrency, and the server simply responds to each connection check request in the order it comes in. Eventually, the waiting requests time out and all remaining agents abort their connection, requiring the whole process to begin again for clients that were stuck in the queue.

Our question is three part:

A.) Is there something we're missing in order to allow our server to respond to requests in a non-blocking manner?
B.) Is there some way to increase the size of the request queue so that we're not bouncing back requests after a certain number of requests is reached?
C.) Is there any way to attach an affinity or priority level to individual services to give them priority in the queue? E.g. requests from the GUI app take precedence over the connection requests from agent clients

Thanks for your time

**Comment by JamesNK** [comment]
ASP.NET Core servers like Kestrel and IIS can accept connections in parallel and new requests in parallel.

If you have scalability issues, the most likely cause is either thread starvation or insufficient memory. 20,000 HTTP/2 connections is quite a few connections but it should be easy enough to see if your server is running out of memory.

If your code blocks the thread (i.e. `Task.Result` instead of `async/await`) then it's very easy to use up all the threadpool threads and cause the server to not accept new connections or requests until a in the threadpool is available.

See here for debugging threadpool starvation: https://learn.microsoft.com/en-us/dotnet/core/diagnostics/debug-threadpool-starvation
