### ISSUE TITLE
Package signing

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#24]
- [x] Strong naming
- [x] Authenticode signing
- [x] nupkg signing
- [x] Google.Protobuf nupkg/Authenticode signing

**Comment by JamesNK** [comment]
FYI gRPC.Core is already strong named:
`Grpc.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d754f35622e28bad`

**Comment by JamesNK** [comment]
## Option 1 - Use third-party hosted signing service

The .NET Foundation has a hosted signing service for Authenticode and nupkg signing that is very simple to use. You call an API, pass it the NuGet package and the service returns a signed copy. The downside with this approach is you would need to give the certificate you wish to use to a third-party.

## Option 2 - Host signing service yourself

An alternative is hosting the signing service yourself. The source is available at https://github.com/onovotny/SignService. You keep control of your certificate but there is work involved to setup and then administer a new service.

## Option 3 - Use command line as part of the build

Finally you could use the low level tools. signtool for Authenticode and the nuget command line for the NuGet package.

https://docs.microsoft.com/en-us/dotnet/framework/tools/signtool-exe
https://www.digicert.com/code-signing/signcode-signtool-command-line.htm

https://docs.microsoft.com/en-us/nuget/create-packages/sign-a-package

Signing the NuGet package is quite simple. I'm not sure how you would do Authenticode signing because that involves modifying the content of NuGet package with the updated assemblies. @onovotny how does the signing service do this?

**Comment by onovotny** [comment]
For option 1, the project can join the .NET Foundation as well. I don't see any reason a project can only be part of a single foundation. As a .NET Foundation member project, we provide free EV code signing certificates in the project's name (and host the signing services as James mentioned).

For option 3, it's not really magic -- the service unzips the nupkg, signs the inner files, rezips the nupkgs, then signs it. Just need to use the right signing tool for the right thing.

While the signing service is the easiest option that takes care of tracability and security, you can also put the certs on your own key vault and use AzureSignTool and NuGetKeyVaultSignTool against your own vault:

https://github.com/vcsjones/AzureSignTool
https://github.com/onovotny/NuGetKeyVaultSignTool

**Comment by onovotny** [comment]
Strictly speaking, you don't *need* to sign any NuGet package. It's more about whether your customers (corporate customers) will start using the lock-down features to only allow NuGet packages from specific publishers. It's not like strong naming where your dependencies must be strong named too.

**Comment by JamesNK** [comment]
Ah, that was more a question for us to resolve. MS has a requirement about shipping signed assemblies. I think `Google.Protobuf` would also need to be shipped and so would also need to be signed. That would mean it wouldn't just be a matter of the gRPC project becoming .NET Foundation member to solve signing (not that I'm pushing that as the best solution, it would involve lawyers and stuff which would be a pain in the butt!), because that would still leave `Google.Protobuf` to do.

@jtattermusch do you know who owns `Google.Protobuf`?

**Comment by kkm000** [comment]
FWIW, Grpc.Core depends on and loads native code at runtime: .dll, .dylib, .so, depending on runtime platform.

**Comment by jtattermusch** [comment]
@JamesNK the google protobuf team owns Google.Protobuf, but I believe I can represent Google.Protobuf C# in this discussion. They are using the same infrastructure (kokoro CI) for building nuget packages as gRPC does.

I agree that protobuf joining .NET foundation seems troublesome (it seems complicated for gRPC as well).
Our CI has a way to sign packages with google's certificate I believe, but there is some technical complexity setting this up, I experimented with that in the past without much success, but I can give it another try.
If all the nugets (Grpc and protobuf) are signed with google's certificate, would that be fine for you? (AFAIK the nuget should be signed by the entity that built them, which is google in our case).

**Comment by JamesNK** [comment]
Authenticode signing the assemblies in the NuGet package is as important as signing the NuGet package for us. I'll double check with our security guys how important it is.

@onovotny With modern SDK based csproj files the `pack` command outputs a nupkg. Do you know of a hook that allows the assemblies placed in the nupkg to be signed during build?

**Comment by onovotny** [comment]
I'm not sure, but I generally advise against that as well since that means there are secrets running in the build agent in the same build step. Given that a build script can do arbitrary things, it's more risk of secret leakage if it's in the main build instead of in a discreet step.

Easiest thing is prob to do the pack, then unzip to a specific dir, sign what you need, then rezip.

**Comment by JunTaoLuo** [comment]
@jtattermusch what work is remaining here?

**Comment by onovotny** [comment]
I'll take a look this evening

**Comment by onovotny** [comment]
I noticed you're referencing Ix Async 3.1.1? That's ancient...why not use 3.2.0?

**Comment by onovotny** [comment]
this package looks bad. digging for the error but not all zip is the same.

**Comment by JamesNK** [comment]
https://github.com/grpc/grpc/issues/17976

**Comment by onovotny** [comment]
Here's what I see in the debugger, and the exception is coming from NuGet: 

![image](https://user-images.githubusercontent.com/1427284/52449954-1777bf80-2b07-11e9-9f6c-a99ca09d6471.png)

**Comment by onovotny** [comment]
This is related https://stackoverflow.com/questions/27289115/system-io-compression-zipfile-net-4-5-output-zip-in-not-suitable-for-linux-mac

**Comment by jtattermusch** [comment]
@onovotny  thanks for the investigation!  Yes, no I recall that we experienced some problem with powershell-based zips in the past. I'll try to use 7z.

**Comment by kkm000** [comment]
I see arm64-v8 in the stack trace, while the failing library is x86/libgrpc...so. Is this expected?

**Comment by JamesNK** [comment]
Gprc.* packages are signed. Leaving this open until Google.Protobuf is signed

https://github.com/protocolbuffers/protobuf/issues/5756

**Comment by jtattermusch** [comment]
Google.Protobuf packages 3.7.0 have been pushed and they are signed.
