### ISSUE TITLE
Memory keep going up and never go down

### ISSUE THREAD

**Issue by wisamidris7** [grpc/grpc-dotnet#2508]
I used a the normal grpc service template and I did a threading and 100,000,000 word request 
Cause my requirements for grpc is a peer to peer data transformation so the data is gonna be exceeding 15mb 

When I created a empty grpc application when I made a test application that makes a lot of requets
I found out that it keeps taking memory without garbage collecting when it got into ~300mb it has been stuck there until another request come and high it up and never go down

And this is video when I did the steps that made this issue

https://github.com/user-attachments/assets/2836751a-1db1-4028-8692-681a854cd2a0

And the application here is a zip file for it

[GrpcService3.zip](https://github.com/user-attachments/files/16619093/GrpcService3.zip)

And you can try it with your self and try to fixing it cause grpc must be mutant for many requests and long body

**Comment by kalduzov** [comment]
This is not a bug, this is a feature of the system.io.pipelines that underlie the processing of requests on kestrel. The internal pipe buffer (sequence) for reading data from the socket at high RPS for the connection will always only increase, but not decrease. And the larger the request size, the more actively this buffer will increase, so that all data in this connection is successfully processed.

Either in the runtime or aspnet project there is an issue in which the creation of a mechanism for truncating unused blocks in this place is discussed.
