### ISSUE TITLE
Add logging bindings for Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by jtattermusch** [grpc/grpc-dotnet#3]
https://www.nuget.org/packages/Microsoft.Extensions.Logging/ seem to be the standard used by ASP.NET core. gRPC C# currently uses its own logging API, we will probably need an adaptor.

**Comment by jtattermusch** [comment]
CC @JunTaoLuo

**Comment by csteegz** [comment]
So the idea is that the current code could keep using the GRPC ILogger? Is the idea that the DI would only happen at the GRPCEnvironment level? I'd love to help get some of this stuff up and running (albeit in my free time)

**Comment by JunTaoLuo** [comment]
I'm wondering what is the goal of the logging bindings are here.

From what I can see currently, it looks like the current ILogger in GRPC is used to log information specific to types used by the c core server such as `AsyncCall`, `NativeExtension`, `GrpcThreadPool`, etc. Since we are not using the c core server here, I'm not sure if we need the logging adapter to redirect current GRPC logs to our logging infrastructure.

There is a case to be made to update the logging in the c core server to use Microsoft.Extensions.Logging as well if that's what you intend but I think that would be a parallel effort that should be filed in grpc/grpc instead.

**Comment by JunTaoLuo** [comment]
I do see a potential need for an adapter depending on how and where serialization/deserialization is implemented though.

**Comment by JamesNK** [comment]
Is this still wanted? As far as I can tell Grpc.AspNetCore.Server will never use the gRPC logger. The server will write directly to ASP.NET Core's logging infrastructure.

We can create a logger but it would used by the native client when calling gRPC from a server.

**Comment by JunTaoLuo** [comment]
@jtattermusch one of the considerations here is that we moved the ILogger types to Grpc.Core.Api in https://github.com/grpc/grpc-dotnet/issues/1 in anticipation to support this feature. I'm wondering if that was a little premature since we haven't decided on how to proceed on this issue yet. In case we don't get to this immediately, maybe we should only move the ILogger types back?

**Comment by JamesNK** [comment]
I'm going to close this. There doesn't seem to be any interest. Can reopen in the future if there is demand.

**Comment by msschl** [comment]
@JamesNK Is there a sample on how to enable logging in blazor webassembly?
