### ISSUE TITLE
Accessing HttpContext in a gRPC service call

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#36]
gRPC C# offers the `ServerCallContext` with information about the current call. Currently there is no way access the underlying `HttpContext` from service methods.

- [ ] Decide if HttpContext should be accessible
  * Service base class?
  * Service interface?
  * Include it as part of `ServerCallContext`. Get with extension method?
- [ ] Implementation

**Comment by jtattermusch** [comment]
Accessing HttpContext should be more of an exception than a rule. No other gRPC implementation exposes "raw" details about the transport layer (among other reasons, gRPC should be transport layer agnostic). I'd say we should only expose HttpContext if it turns out to be necessary and it should be considered more of a workaround rather than a supported feature.

If we do need to expose HttpContext,  extension method on `ServerCallContext` seems like a good approach.

**Comment by JamesNK** [comment]
It will be useful for accessing values set on the HttpContext by middleware. I will definitely be the exception, mostly for power users.

**Comment by JamesNK** [comment]
Blocked on ServerCallContext
