### ISSUE TITLE
Correlate service calls through ContextPropagationToken

### ISSUE THREAD

**Issue by JunTaoLuo** [grpc/grpc-dotnet#40]
We need to explore the API required to trace service call by propagating the `ContextPropagationToken`. The goal is to be able to trace an entire call chain, regardless of implementation.

**Comment by JunTaoLuo** [comment]
https://github.com/dotnet/corefx/blob/master/src/System.Diagnostics.DiagnosticSource/src/ActivityUserGuide.md

**Comment by JamesNK** [comment]
Blocked on ServerCallContext

**Comment by JamesNK** [comment]
`ContextPropagationToken` has an internal constructor. Making the constructor public and returning a default implementation doesn't add any value. The way the token works today is the ccore client casts to an internal type, which Grpc.AspNetCore.Server has no access to.

The current way the token is structured has problems. Relying on casting to an internal type means that the client and the server need to share that type. This isn't an issue with ccore because the client and server share the same attribute. For a managed client an implementation of `ContextPropagationToken` will need to be in a shared package and public so they can both talk with it.

I think `ContextPropagationToken` should be extended to provide a real abstract API that provides all its capabilities: deadline, cancellation token, tracing. That removes the need to cast to a known implementation, and has the benefit of the ccore client being able to use `Microsoft.AspNetCore.Server`'s propagation token, and a new .NET Core 3 `HttpClient` client could use the ccore server's.

```cs
public abstract class ContextPropagationToken
{
    public abstract DateTime Deadline { get; }
    public abstract CancellationToken CancellationToken { get; }
    public abstract string TraceId { get; } // or whatever is used for tracing
}
```

**Comment by jtattermusch** [comment]
FTR, the different kinds of context that can be propagated by C-core: https://github.com/grpc/grpc/blob/b28820ded677a7e48b224661f42b1255abf63034/include/grpc/impl/codegen/propagation_bits.h#L28

**Comment by JamesNK** [comment]
@jtattermusch How is tracing via the propagation token sent over the wire in HTTP? Do you follow an existing standard? Is it dapper or opentrace? Is there consensus in gRPC with how tracing is done.

**Comment by jtattermusch** [comment]
@JamesNK the default tracing supported by gRPC is opencensus. More documentation is available here: https://opencensus.io/introduction/

Specifically
> OpenCensus supports several different context propagation formats, and is the reference implementation of the official W3C HTTP tracing header.

**Comment by JamesNK** [comment]
Python, Java, C++ has OpenCensus examples.

**Comment by JamesNK** [comment]
I don't think this is needed. I don't think correlating calls between an app that is using both Grpc.Core and grpc-dotnet is that valuable, and in .NET Core we have `Activity` to propagate telemetry.

Can reopen if a use case for ContextPropagationToken is identified.

**Comment by abe545** [comment]
@JamesNK can you help me understand why this is not needed? At Namely, we have grpc services written in `go`, `python` & `c#` - we currently propagate deadline + cancellation between all 3 (we haven't migrated off `Grpc.Core`). Are we mistaken that this actually works from the `c#` and `python` services to `go`? If it does currently work, why do you think it isn't valuable to have this propagation work with `grpc-dotnet` (or are those 2 supported, but not the tracing)?
We wrote client + server interceptors to support the zipkin traces we currently use - but if we could use built-in support for propagating tracing, that would be ideal.
