### ISSUE TITLE
Client operation cancellation doesn't follow API guidelines

### ISSUE THREAD

**Issue by marklio** [grpc/grpc-dotnet#407]
When cancelling client operations, it seems common to get a Grpc.Core.RpcException with status code "Cancelled". This makes it very difficult to deal with cancellation through a broader stack, where normally you'd get something in the OperationCancelledException type hierarchy and the task would appropriately be marked IsCancelled rather than IsFaulted.

Consider a library where Grpc is used as an implementation detail. An operation that is cancelled can have wildly different behaviors depending on where in the implementation cancellation is "triggered". If it's in the library, you'll get standard cancellation behavior. If it happens to trigger during a Grpc operation, you'll get what looks like "fault" behavior. The deeper in the stack Grpc is used, the more baffling this behavior will appear.

**Comment by JamesNK** [comment]
@jtattermusch I followed Grpc.Core's client behavior when raising the cancelling token which is throwing RpcException with a Cancelled status. What do you think about throwing OperationCancelledException instead?

**Comment by jtattermusch** [comment]
Returning an RPC error with status "Cancelled" when an RPC gets cancelled is basically required by the gRPC spec: https://github.com/grpc/grpc/blob/master/doc/statuscodes.md. I understand there might be situations in your applications where it might be feel convenient for a cancelled RPC to throw OperationCancelledException, but gRPC is an RPC framework and we shouldn't be trying to pretend it's not - if an RPC fails with with a particular status code and message, we should expose it as such.

Another reason why we cannot do this is that because it would be a breaking change.

In don't know your particular use case, but it should be possible to convert RpcException with status code "Cancelled" into OperationCancelledException relatively easily (extension method?).

**Comment by marklio** [comment]
FWIW, this is not "my" use case. This is anyone using the standard cancellation model in managed code. Cancellation is a special case for the task/async infrastructure in dotnet (separate from "fault"), and gRPC does not conform. In addition to the things I mention above, this also means that diagnostic features around cancellation don't work. As to the "spec", we're already transforming success responses into "normal" dotnet types. We're already transforming error conditions as "normal" dotnet exceptions. There are already non-rpc exceptions that can flow out of the code.  It makes sense to map cancellation to the "normal" dotnet pattern. As to the breaking nature of such a change, believe me that I hear and respect this position. It could be opt-in behavior (perhaps triggered automatically based on the target framework). The dotnet SDK support for gRPC already handles lots of the details for folks, it could easily handle a switch for this (or even do the actual mapping) from the cancelled status to the regular pattern.

**Comment by jtattermusch** [comment]
@marklio  thanks for the explanation. Do you have a change proposal in mind? 
Ad making this an "opt-in behavior": I'm generally not a fan of opt-in modes of operation, because they are hard to maintain and test and it's easy to and up with each user doing something different (which isn't good for anyone).

**Comment by JamesNK** [comment]
GrpcChannelOptions has a new property to control this behavior. Developers can opt-in to have the client throw OperationCanceledException on cancellation.
