### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by shirhatti** [grpc/grpc-dotnet#510]
We currently don't have any API documentation for this project.

I see the existing documentation lives at https://github.com/grpc/grpc/tree/gh-pages/csharp/api.

@jtattermusch What do we want to do here? Do you think it's reasonable to just update those docs there to include grpc-dotnet?

cc @JamesNK @JunTaoLuo

**Comment by jtattermusch** [comment]
Because grpc-dotnet is in a sense ASP.NET Core and also most of grpc-dotnet's documentation is on the ASP.NET core documentation site, perhaps it makes sense for the API docs to live where the rest of ASP.NET core API docs live as well?

If you prefer to have the API docs on grpc.io site, we could another entry ("grpc for .NET") under https://grpc.io/docs/reference/ and then the generated docs would be added by merging to the "gh-pages" branch. 

gRPC C# currently uses docfx to regenerate the docs: https://github.com/grpc/grpc/tree/master/src/csharp/docfx

**Comment by shirhatti** [comment]
Deferring to @danroth27, since he knows best how ASP.NET generates API documentation. Is it even possible to include API docs from an external repo in the ASP.NET docset?

**Comment by danroth27** [comment]
It's technically possible. The API ref docs can be generated based on the NuGet packages as long as they contain the XML doc files. However, I don't think we want the ASP.NET Core API ref docs to become the single doc repository for all ASP.NET Core related things. I don't think we're setup for that.

**Comment by JamesNK** [comment]
Done
