### ISSUE TITLE
Resolver/Balancer API

### ISSUE THREAD

**Issue by monomosc** [grpc/grpc-dotnet#521]
Grpc Implementations generally favor or at least support Client-Side-Loadbalancing. In Go you go
```go
chan, err := grpc.Dial("my-custom-resolver://some-string-that-has-meaning/some-other-string-with-meaning")
```
which will basically call a previously registered resolver (```my-custom-resolver```) with the URL. This resolver then has the job to return 0 or more IP Addresses to finally connect to. It might query SRV records from a DNS resolver, or ask something like etcd, zookeeper, consul, etc...

There is also the old API where you pass ```grpc.WithBalancer(myBalancer)``` to ```grpc.Dial```. I suspect this fits C# better.

How will this be achieved in grpc-dotnet?

**Comment by jtattermusch** [comment]
Currently grpc-dotnet doesn't support client-side loadbalancing (or lookaside loadbalancing). This is a feature that might be implemented in the future, but currently there's no ETA. Our ability to implement it depends a lot on what functionality does the underlying layer provide (HttpClient in case of grpc-dotnet), we need to look into that in detail.

**Comment by monomosc** [comment]
Do you think it would be feasible to write a CallInvoker (or maybe a ChannelBase) which implements round-robin Dispatch? I would experiment with it for my use-case and return with a Demo-PR if you think that could possibly be considered.

**Comment by JamesNK** [comment]
How does client-side/lookaside load balancing typically work in other implementations?

When does the channel/call invoker query a resolver (like DNS resolver) to get a list of available endpoints to call? Does it happen when the balancer is created, periodically in a background timer, or just prior to calls being made?

My hunch is load balancing will be external to `HttpClient`. If all it involves is selecting a target address, that logic can be executed and then the selected address is passed to `HttpClient`.

**Comment by jtattermusch** [comment]
@apolcyn has more details on how exactly resolution works.

My understanding (might be a slightly inaccurate / oversimplified version of reality) is that the "simple" (e.g. round_robin) loadbalancing works like this:
1. name resolution only happens once a call is attempted (or a connection is forced via connectivity API)
2. multiple backends might be resolved from a single DNS address
3. round_robin LB must be explicitly configured (otherwise pick_first strategy is used)
4. if there are multiple backends, gRPC round robins over N connections ("subchannels") at the call level (two successive calls go to different subchannels).
5. re-resolution only happens if there's a connection failure (there's some disagreement about this rule, but that's currently the behavior gRPC C core has).

The scenario with "lookaside" loadbalancing is much more complicated that that and currently we're in the process of implementing support for xDS protocol loadbalancing (same loadbalancing that envoy proxies use). The idea is similar to grpclb loadbalancing, but grpclb protocol doesn't have much support in the open source world (unlike the xDS protocols).

Some more details from the docs:
https://github.com/grpc/grpc/blob/master/doc/load-balancing.md
https://github.com/grpc/grpc/blob/master/doc/naming.md
https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md
https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md

**Comment by jtattermusch** [comment]
Some useful resources on gRPC loadbalancing basics and examples for the scenarios described above are here: https://github.com/jtattermusch/grpc-loadbalancing-kubernetes-examples (note that none of this is currently implemented in grpc-dotnet).

**Comment by apolcyn** [comment]
@jtattermusch I would generally agree with your description too.

However, note though that one client side load balancing policy implementations pick their addresses with a a bit smarts than just the way that resolved address lists are iterated over. One thing to note in particular is that generally client side load balancing "policy" implementations rely on being able to monitor "connectivity state" of "subchannels" (each "subchannel" sounding like it would probably be one `HttpClient` targetting a single IP address). This is the case even for simpler policies like pick_first and round_robin. In very short,  policies use this in order to know things like, when an address is ready to be selected for an RPC, when to skip over an address, and when to re-resolve.

Is there a way that a policy can monitor `HttpClient` "connectivity state"s (as modeled in https://github.com/grpc/grpc/blob/master/doc/connectivity-semantics-and-api.md)? Or in some other way know the "health" of an HttpClient connection? 

This might be worth a doc to review with folks from other grpc languages once hashed out more.

**Comment by monomosc** [comment]
I hacked something together, and as @apolcyn has said, the only building block missing to reach parity with the golang *Balancer* and *Resolver* API surface (which exists almost purely in abstractions) is some way to get connection health status of a ```HttpClient```. Of course you could also defer this the GrpcChannel/Balancing CallInvoker, which would then have to track ```RpcException```s.

**Comment by JamesNK** [comment]
Nice. Are you able to share the source code? It doesn't need to be perfect. I'm curious to see what you came up with.

Yes, I think querying `HttpClient` is the blocker here to creating something robust.

@apolcyn Are there any specs around what a gRPC load balancer should do or does behavior differ depending upon the implementation for a language? Do you have a load balancer implementation you would recommend to aspire to?

**Comment by monomosc** [comment]
I have approximated my Code in a [gist](https://gist.github.com/monomosc/86917a57f0c1561589dcfb559d2d92b6). Check out the file called **RelevantCode.cs**, ignoring ~~Boilderplate.cs~~. This does not exactly capture what I'm using internally (which I can maybe share after asking too many people), but it matches it in spirit. It's actually abstracted better.

Issues I could identify

 - I have no idea how to write an async CallInvoker. The methods all do not return a Task. It seems I'd have to build my own AsyncUnaryCall<TResponse> with its public constructor. Ugh.
 - Is a resolver responsible for checking availability of a host, or is it the balancers job?
 - There are probably race conditions in there
 - Cancellation

**Comment by Somuynews** [comment]
https://gin-gonic.github.io/gin/

**Comment by apolcyn** [comment]
@JamesNK sorry there isn't currently a formal detailed spec for LB policy behavior, however the existing language stacks have tended to aim for consistency amongst each other.

**Comment by leyou240** [comment]
In my opinion, we can use the service registration pattern to support loadbalancing(pick first, roundrobin, weightroundrobin etc...). 
[https://dzone.com/articles/service-discovery-in-a-microservices-architecture](https://dzone.com/articles/service-discovery-in-a-microservices-architecture)
[https://github.com/grpc/grpc-java/issues/428](https://github.com/grpc/grpc-java/issues/428)

**Comment by wicharypawel** [comment]
Hi, I think I have something interesting to share. The last few days I've been working on a better understanding of load balancing in grpc. I have expanded the capabilities of grpc dotnet with full support for load balancing. 

I think it's something of a worth looking at. I prepared two repositories:

The first repository contains fork repository grpc dotnet with extension of grpc.net.client capabilities (currently this branch has only one commit because all my work was squashed to erase some wrong ideas of mine 😄 )

link: https://github.com/wicharypawel/grpc-dotnet/commits/load-balancing-for-dotnet 

Extensions include: (documentation links below)
- support for subchannels
- pick_first policy
- round_robin policy
- grpclb policy
- naive resolver plugin (for non-loadbalancing scenarios)
- dns resolver plugin (works with SRV and TXT records)
- static resolver plugin (for local work)
- support for dns:// scheme
- support for overriding dns server while working with dns resolver plugin 
- base support for service config via TXT records
- includes verbose logging

Basically this one commit can add full blast support. 

The second repository is an example of using this implementation and ton's of other examples and snippets

link: https://github.com/wicharypawel/net-core-grpc-load-balance

Samples include:
- round robin for gRPC dotnet client
- lookaside load balancing for gRPC dotnet cient
- lookaside load balancing for gRPC dotnet cient with custom dns server
- include dummy C# implementation of lookaside loadbalancer for gRPC in K8s
- and 5 other scenarios including samples for lookaside loadbalancing in Go, Python and Java

Kudos to @jtattermusch for his presentation about grpclb available here: https://github.com/jtattermusch/grpc-loadbalancing-kubernetes-examples

Related documentation:
- https://github.com/grpc/grpc/blob/master/doc/load-balancing.md
- https://github.com/grpc/grpc/blob/master/doc/naming.md
- https://github.com/grpc/grpc/blob/master/doc/service_config.md
- https://github.com/grpc/proposal/blob/master/A5-grpclb-in-dns.md
- https://github.com/grpc/proposal/blob/master/A2-service-configs-in-dns.md 
- https://github.com/grpc/proposal/blob/master/A24-lb-policy-config.md
- https://github.com/grpc/grpc-proto/blob/master/grpc/service_config/service_config.proto

Hope you find this help full, I would be glad to help if you find that interesting to pull request.

**Comment by jtattermusch** [comment]
@wicharypawel  thanks for posting the contribution, it looks interesting. I'll try to take a closer look soon.

**Comment by wicharypawel** [comment]
@jtattermusch I am working with this code base daily, be sure to pull latest changes. Moreover, in order to reduce information noise I am adding information about new extensions to the previous post as edits.

**Comment by wicharypawel** [comment]
Based on chat with @jtattermusch, previously described work will be posted as official proposal in https://github.com/grpc/proposal repository.

Recommended scenario is to split work into smaller parts and create separate proposals, in areas of:
- name resolution and resolver plugin
- service configs for resolution extension
- basic policies which include pick_first and round_robin
- grpclb policy

**Comment by wicharypawel** [comment]
Hello @JamesNK I would like to ask for advice as you are mostly author of the code base. Yesterday, I added one more feature to the codebase, which made some tests fail nondeterministic, when run together.

Could you tell me if there is any shared state between the tests that I should be aware? My case influence multiple tests but as an example let's focus on AsyncClientStreamingCallTests.cs 

Some info that may be helpful:
- running tests sequentially results in passing suite
- new feature is about buffering calls that are awaiting for loadbalancer to be ready (so called buffer is created per each GrpcChannel with no other shared state)

Example stack trace
```
  Message: 
    System.Exception : Exception of type InvalidOperationException expected; got exception of type RpcException.
      ----> Grpc.Core.RpcException : Status(StatusCode=Unimplemented, Detail="Bad gRPC response. HTTP status code: 404")
  Stack Trace: 
    ExceptionAssert.ThrowsAsync[TException](Func`1 action, String[] possibleMessages) line 52
    TaskExtensions.TimeoutAfter[T](Task`1 task, TimeSpan timeout, String filePath, Int32 lineNumber) line 59
    AsyncClientStreamingCallTests.ClientStreamWriter_WriteWithInvalidHttpStatus_ErrorThrown() line 222
    GenericAdapter`1.BlockUntilCompleted()
    NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
    AsyncToSyncAdapter.Await(Func`1 invoke)
    TestMethodCommand.RunTestMethod(TestExecutionContext context)
    TestMethodCommand.Execute(TestExecutionContext context)
    SimpleWorkItem.PerformWork()
    --RpcException
    HttpContentClientStreamWriter`2.WriteAsyncCore(TRequest message) line 175
    ExceptionAssert.ThrowsAsync[TException](Func`1 action, String[] possibleMessages) line 32
```

**Comment by wicharypawel** [comment]
Hello, 
I would like to share the results of my work. Let me share draft version of the proposal that aims for introducing load balancing in gRPC for dotnet. 

[grpc-dotnet load balancing support proposal (and related proposals).pdf](https://github.com/grpc/grpc-dotnet/files/4711275/grpc-dotnet.load.balancing.support.proposal.and.related.proposals.pdf)

After having initial review I would like to make pull request into official gRFC proposals repo.

Fork with the code is shared here: https://github.com/wicharypawel/grpc-dotnet/tree/load-balancing-for-dotnet (commit hash: efd5eda4633acf97380146677ab8b985fa9abf9e)
Example usage of this new feature is shared here: https://github.com/wicharypawel/net-core-grpc-load-balance/tree/load-balancing-proposal-examples (commit hash: f0628b80c469fb21502d527b8ccc85b005fe9ed2)

**Comment by JamesNK** [comment]
Wow. I'll take a look over the next couple of days.

**Comment by wicharypawel** [comment]
Hey @JamesNK, take your time, as even if I would apply proposal for formal review I guess it will take gRPC team, a while to get it covered.

If you would like to have a call on hangouts to get high-level intro how it works, it would be my pleasure (contact me by email). I have spent last 5 months to keep mastering gRPC by reading official docs, proposals, reading gRPC Java implementation and doing gRPC examples. I feel confident to speak both high-level and in-depth implementation details.

**Comment by wicharypawel** [comment]
For anybody interested in this topic. It is blocked until gRPC team will accept gRFC proposal, which is mentioned above this comment, as it contains a internal API design ported from gRPC for Java implementation.

**Important**: working implementation already exist as a fork, for more information see previous comments.

**Comment by JamesNK** [comment]
I'm looking into load balancing more seriously now, and reviewing the content of your PR.

The right pieces are in the PR, but I want to refactor a lot of the implementation. Some Java concepts like SyncContext, and Rx are Java idioms required in Java libraries because of the lack of async/await. I think we can simplify while keeping most or all of the current features.

**Comment by wicharypawel** [comment]
Hi, James,
I agree with you, all language idioms related to Java should be replaced by C# equivalents. Let me list the reasons why I initially took such steps:
- to make it easier to review the code for people who are experienced in the implementation of gRPC Java
- to simplify the porting process, I wanted to focus on the correct functioning

In other words, feel free to propose chages to proposal.

**Comment by JamesNK** [comment]
I looked a little more at your PR. As far as I can tell the connectivity status for each subchannel will always be READY because HttpClient lacks low-level APIs for looking at the underlying HTTP/2 connection.

If that is the case, does the pick_first balancer have much use? Won't the channel always attempt to use the first subchannel?

**Comment by wicharypawel** [comment]
Subchannel state is changing, it may be surprising but I have managed to make mechanism that workarounds missing low-level api support. The way it works was described in proposal.

**Comment by wicharypawel** [comment]
Hi @JamesNK 👋  I'm curious if you tried out this implementation?

**Comment by JamesNK** [comment]
Yeah I have. Right now I'm focusing on IPC (i.e. gRPC over namedpipes/UDS) for .NET 5, but I'll look at load balancing more once I have that working.

**Comment by mjsabby** [comment]
After reading about xDS I was searching if grpc-dotnet had this implementation. So I'm glad it's at least got some legs.

However, is there a point to implement anything beyond xDS? Given that's the direction of gRPC?

Maybe interim support? I'm just curious.

**Comment by houseofcat** [comment]
@JamesNK Know you are busy, but any updates on this?

**Comment by wicharypawel** [comment]
@mjsabby xDS is the desired solution, but as far as I know it is still being formed for Java and Go. Other options like round robin are there for regular use (but they are mature in my perspective), however gRPC for .NET has not been focused on this. I have implemented the structure and basic policies but I can't PR it as soon as the proposal will be accepted.

@houseofcat If you are looking for a working no-official implementation check my repository:
- Fork with the code is shared here: https://github.com/wicharypawel/grpc-dotnet/tree/load-balancing-for-dotnet
- Example usage of this new feature is shared here: https://github.com/wicharypawel/net-core-grpc-load-balance/tree/load-balancing-proposal-examples

**Comment by houseofcat** [comment]
@wicharypawel thanks I will see if this is viable for my needs!

**Comment by sunliusi** [comment]
any updates on this?

**Comment by jtattermusch** [comment]
@JamesNK is working on a design in https://github.com/grpc/proposal/pull/240

**Comment by pcwiese** [comment]
Has there been any movement on a design/implementation to support the xDS protocol for parity with Go, Java, C-core wrapped langs? My team currently uses the grpclb protocol with the C# wrapper over Grpc.Core and we understand the need to move away from it well before May 2022. I'd like to get involved in this effort if it will speed up the process.

**Comment by JamesNK** [comment]
Load balancing is coming but only DNS load balancing will be in the first version. I don't know when xDS will happen.

However, the public APIs required to implement xDS should be available, and it could be done in a separate package.

**Comment by pcwiese** [comment]
> Load balancing is coming but only DNS load balancing will be in the first version. I don't know when xDS will happen.
> 
> However, the public APIs required to implement xDS should be available, and it could be done in a separate package.

So in your mind, xDS support doesn't belong in this repo, but in a separate one. Is there already some kind of contrib or extensions repo for add-ons to this one?

**Comment by JamesNK** [comment]
It should belong in this repo but an external contributor can start it independently.

**Comment by JamesNK** [comment]
Load balancing is available now in preview releases.

https://docs.microsoft.com/en-us/aspnet/core/grpc/loadbalancing?view=aspnetcore-5.0
