### ISSUE TITLE
Support shared .NET contracts

### ISSUE THREAD

**Issue by poke** [grpc/grpc-dotnet#68]
Right now, gRPC seems to rely on Protobuf contracts to be shared between server and client. But for a .NET context, `.proto` files are somewhat strange.

I would like having a way to define services as interfaces and data contracts as POCOs in a separate .NET assembly that would then be referenced by both the server and the client. That way, one wouldn’t need to exchange `.proto` files but could rely on .NET mechanisms to share .NET-native types.

In a way, this would be a bit like WCF’s `ChannelFactory<T>` which also allowed you to connect to a hosted service when you already had the contracts around.

---

**@JamesNK - Oct 2019 update:**

`protobuf-net.Grpc` supports code-first gRPC without *.proto* code generation. It builds on top of grpc-dotnet, replacing the code generation serializer with protobuf-net.

protobuf-net.Grpc is available on NuGet today. There are currently no plans to support code-first in grpc-dotnet.

For more information about protobuf-net.Grpc, see https://protobuf-net.github.io/protobuf-net.Grpc/gettingstarted

**Comment by RainingNight** [comment]
Yeah, I use GRPC only on .Net Core，Immediate POCO is very good, `.proto` is tedious.

**Comment by neuecc** [comment]
gRPC itself does not depend protocol buffers and there method definition.
We can register handler manually, it completely works.
I've already tried, and created a framework that built on gRPC.
https://github.com/Cysharp/MagicOnion
Maybe it is not a concern of gRPC Core.
However, if grpc-dotnet is also open to extensibility, such a framework can continue to be developed.

**Comment by Kadajski** [comment]
Why not just use ASP.net core with some kind of client codegen(swagger?). Seems like you'd lose some advantages grpc offers. At least from my limited knowledge of how all this works. Seems like you'd have issues with concepts such as versioning of messages, sharing interfaces with non-.net languages, you'd lose ServerCallContext probably, you'd only probably be able to support unary transport easily.

Since this is all just built on top of ASP.net core APIs though you could create your own extension method and use reflection to try hook all this up on `IEndpointRouteBuilder` though. 
IMO to me this seems like something that if it existed should be a seperate project rather than a core gRPC one as if this was introduced you'd probably end up with loads of issues with some custom implementations built on top of that, which would be difficult to maintain for

**Comment by AlgorithmsAreCool** [comment]
@Kadajski

The point of making this request here is that we want to use GRPC and not a REST based API. GRPC has great features such as bi-directional streaming that are valuable to us.

Libraries like ProtoBuf-Net and even WCF have showed us that versioning POCO definitions is very possible and not overly cumbersome.

Besides, it is not like Protobuf has some magic that allows versioning to always work, you still have to follow rules when you update your definitions.

Lastly we don't want today really have to write a reflection based shim.

We would just like a path forward that allows us to annotate an existing POCO model so that it can be serialized across the wire.

As an aside, magic onion might be that solution but first party support for this scenario would be nice and that is the key ask of this issue.

**Comment by poke** [comment]
@Kadajski Just because you start POCO-first that does not mean that you would lock yourself out of other gRPC clients. I imagine it would be very practical to host a service POCO-first and have a first-party .NET client, and in addition a generated .proto file for other client languages.

And as AlgorithmsAreCool said, gRPC is a different messaging protocol that has certain advantages over REST APIs with standard JSON transfer. Not to mention that REST is a very different approach to RPC. Yes, you can host an RPC API through API controllers, but you will still need to go through quite a few things to make it workable easily.

And designing a REST API with a generated client is still a very different experience to just implementing a service interface and just connecting a client with that exact same interface.

**Comment by rwkarg** [comment]
This is the experience we have with WCF services on .NET Framework apps and would like to maintain in .NET Core. We have attributed interfaces and data contracts that are shared client/server. If we need to share across languages, only then will we generate and publish the contract as part of the build/artifact creation process (.proto or swagger/OpenAPI spec).

**Comment by aL3891** [comment]
This would be super helpful for us as well, we're using service fabric reliable services/actors right now and would like to transition to a more asp.net core based model

**Comment by KarloX2** [comment]
I second this request! We also have loads of POCO + C# interface based service contracts we currently use for WCF (duplex nettcp) communication between .NET processes only. As Microsoft seems to skip WCF in .NET 5, there need to be a replacement and it's very important to have a path to continue with the existing code (maybe with some modifications to the C# code, but please without using a completely new interface definition).

And I think that would be an important argument for others who come from WCF.

**Comment by RainingNight** [comment]
Any news?

**Comment by shaggygi** [comment]
Not sure if this is related, but what if I had an existing set of interfaces for a client and model interface/class objects.  Would there be a way to produce a .proto file and auto-generate the server side code along with a client that implemented the client interface?

**Comment by poke** [comment]
@shaggygi Not with the current implementation, but that's exactly what this request is about: Basically to be able to define service contracts and models in an assembly that can be referenced by both the server and client.

**Comment by shaggygi** [comment]
@poke Thanks for the response.  Great to hear this is what I'm looking for.  Definitely hope this feature makes it in the bits at some point.   Thx

**Comment by AlgorithmsAreCool** [comment]
@shaggygi Have you evaluated https://github.com/Cysharp/MagicOnion? It allows a 'code first' service definition similar to WCF. I don't think it will generate protobuf idl for you however.

**Comment by AlgorithmsAreCool** [comment]
Also of note: https://github.com/mgravell/protobuf-net.Grpc

**Comment by JamesNK** [comment]
protobuf-net.Grpc is now available, which builds on top of grpc-dotnet and adds code-first.

We don't have plans to support this in grpc-dotnet. Closing.
