### ISSUE TITLE
Support for full Framework / .NET Standard 2.0?

### ISSUE THREAD

**Issue by georghinkel** [grpc/grpc-dotnet#710]
Are there any plans to support the full .NET Framework and/or .NET Standard 2.0 in the future?

**Comment by chrisevans9629** [comment]
I am looking at this too for a wpf app we are using

**Comment by JamesNK** [comment]
No plans. .NET Framework doesn't support HTTP/2.

[Grpc.Core](https://www.nuget.org/packages/Grpc.Core/) works on .NET Framework.

**Comment by Pinox** [comment]
Hi @JamesNK 

Do Httpclient not support http/2 in  .net standard 2.0:

var client = new HttpClient() 
{
  BaseAddress = new Uri("https://localhost:5001"),
  DefaultRequestVersion = new Version(2, 0)
};

As you know UWP apps don't support .net standard 2.1 so even supporting .net standard 2 will be of great help to use this in a cross platform solution.  Currently can't upgrade my solution to gRPC because of UWP cross platform code.  This is the only library preventing .net standard 2.0 gRPC to work.

protobuf-net.Grpc  and Grpc.Core  supports .net standard 2.0
