### ISSUE TITLE
Kestrel ListenUnixSocket

### ISSUE THREAD

**Issue by Zetanova** [grpc/grpc-dotnet#730]
I am desperately trying to get only a gRPC server over Unix socket to work
with `opt.ListenUnixSocket("/mydir/mysocket.sock")` to work.

Can it be that only Kestrel supports LinuxUnixSocket but not grpc-dotnet?

**Comment by Zetanova** [comment]
The socket is working, 
but following error is thrown on connection: Microsoft.AspNetCore.Connections.ConnectionAbortedException: Invalid Host header: 'csi/csi.sock'
 
The client is a golang kubernetes  from https://github.com/kubernetes-csi/node-driver-registrar
and kubelet is fails too. It tries with the absolut hostPath. 

I tried  `{ AllowedHosts: "*" }` and without the setting and cant find anything to disable the Host header check.

**Comment by anurse** [comment]
> but following error is thrown on connection: Microsoft.AspNetCore.Connections.ConnectionAbortedException: Invalid Host header: 'csi/csi.sock'

This seems somewhat expected since `/` is not valid in an HTTP `Host` header. Since you're using a Unix socket, is it possible to configure your client to send a different `Host` header as a workaround? I'll file a matching bug on dotnet/aspnetcore to consider what we can do to be more generous in Kestrel.

**Comment by anurse** [comment]
> I tried `{ AllowedHosts: "*" }` and without the setting and cant find anything to disable the Host header check.

To clarify a bit. The request is failing `Host` header **validation**, which is part of Kestrel and verifies if the `Host` header is valid [according to the HTTP spec](https://tools.ietf.org/html/rfc3986#section-3.2.2). The `AllowedHosts` setting is for validating that the `Host` header matches an expected set of values, so that's why setting `AllowedHosts` to `*` doesn't work.

**Comment by anurse** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/18522

**Comment by Zetanova** [comment]
seeing it only now and i filed now one too.
https://github.com/dotnet/aspnetcore/issues/18533

@anure All kubernetes golang libs including the kubelet daemon itself are connection with the socket path in http2 authority header field.

I will try to setup an proxy container to override it as a workaround.

**Comment by JamesNK** [comment]
This isn't an issue in the .NET gRPC library. Lets centralize discussion at https://github.com/dotnet/aspnetcore/issues/18522
