### ISSUE TITLE
Connection timeout

### ISSUE THREAD

**Issue by Daniel15** [grpc/grpc-dotnet#735]
Is there a way to specify a **connection** timeout? For example, fail if it takes longer than 5 seconds to connect to a server, but if it does connect within that time frame, allow the call to take longer?

I have a use case where some gRPC services may sporadically not be available, and it seems like the client sits for a long time waiting to connect. Some of these legit calls could take 30-40 seconds which is fine, but I want to fail the request if the connection isn't established within a few seconds.

**Comment by JamesNK** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=netcore-3.1

ConnectTimeout?

**Comment by Daniel15** [comment]
That sounds right, but there's no docs on what it actually does (https://docs.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler.connecttimeout?view=netcore-3.1#System_Net_Http_SocketsHttpHandler_ConnectTimeout is basically blank), and I'm not sure how to set this value within the context of the gRPC client. Do I need to create my own `HttpClient` instance and pass it in?

**Comment by Daniel15** [comment]
Thanks for the pointer... This *appears* to work correctly:
```csharp
GrpcChannel.ForAddress(endpoint, new GrpcChannelOptions
{
	DisposeHttpClient = true,
	HttpClient = new HttpClient(new SocketsHttpHandler
	{
		ConnectTimeout = TimeSpan.FromSeconds(3)
	})
})
```

Closing out this issue.

**Comment by Daniel15** [comment]
Actually, I do have another question... When a timeout does occur, the exception message is:

```
Status(StatusCode=Cancelled, Detail="Error starting gRPC call.")
```

Is there a way to tell that the call failed due to a connection timeout? The exception does not have any `InnerException` or anything else that explicitly states that it failed due to a connection timeout.

**Comment by JunTaoLuo** [comment]
It looks like the `SocketsHttpHandler` throws an `OperationCanceledException`. For this scenario, you would be able to set the option [`GrpcChannelOptions.ThrowOperationCanceledOnCancellation`](https://github.com/grpc/grpc-dotnet/blob/ae359824409e71e3afed2d4b630720fddb7b56eb/src/Grpc.Net.Client/GrpcChannelOptions.cs#L91-L97) which [preserves](https://github.com/grpc/grpc-dotnet/blob/02282330c90151bc2834def73127d485ce3a1464/src/Grpc.Net.Client/Internal/GrpcCall.cs#L513) the exception instead of throwing a `RpcException`. This may be sufficient for distinguishing the failure mode.

A few other notes: we might want to do a better job at logging these types of errors. Currently the exception message is ignored in the logs: https://github.com/grpc/grpc-dotnet/blob/ae359824409e71e3afed2d4b630720fddb7b56eb/src/Grpc.Net.Client/Internal/GrpcCallLog.cs#L42-L43. Also, currently the `RpcException` API doesn't have overloads where we can set inner exceptions. We can consider adding them.

**Comment by JunTaoLuo** [comment]
@Daniel15 did the option I mentioned help your scenario? Since there hasn't been any responses, we'll be closing the issue in 3 days if there are no further updates.

**Comment by Daniel15** [comment]
Yeah, this is fine, thanks!
