### ISSUE TITLE
HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface  

### ISSUE THREAD

**Issue by dingsongjie** [grpc/grpc-dotnet#802]
Change the server configuration of the [sample](https://github.com/grpc/grpc-dotnet/tree/master/examples/Browser) to Kestrel, and then connect aspnetcore grpc-web through Http protocol , The following error occurred:
```log
dbug: Microsoft.AspNetCore.Server.Kestrel[29]
      Connection id "0HLTV45E8MTR4": HTTP/2 connection error.
Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2ConnectionErrorException: HTTP/2 connection error (PROTOCOL_ERROR): Invalid HTTP/2 connection preface.
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ParsePreface(ReadOnlySequence`1& buffer, SequencePosition& consumed, SequencePosition& examined)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.TryReadPrefaceAsync()
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http2.Http2Connection.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

But using iisexpress to start the service, and the client connects through the http protocol, it works fine

**Comment by anurse** [comment]
Can you provide your `appSettings.json` and any modifications you made to the sample to change it to Kestrel? This is a scenario we generally expect to work (and has in the past) so having the full context will help identify what might be different now.

**Comment by dingsongjie** [comment]
> Can you provide your `appSettings.json` and any modifications you made to the sample to change it to Kestrel? This is a scenario we generally expect to work (and has in the past) so having the full context will help identify what might be different now.

I removed all Kestrel related configuration in appsetting, and this is my **Program.cs**
```cs
               .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                    webBuilder.UseKestrel(option =>
                    {
                        option.ListenAnyIP(82, config =>
                        {
                            config.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http2;
                            //config.UseHttps();
                        });
                    });
                });
```

If you start debugging in visual studio in console , do not use IIS EXPRESS , then use javascript grpc-web client to connect it , you will see this error if you  set **"Microsoft.AspNetCore.Server.Kestrel": "Debug"**

When you set **config.UseHttps()** , the javascript client connect will success

**Comment by JamesNK** [comment]
This is failing because you are trying to call a HTTP/2 only port without TLS (HTTPS). That isn't supported by browsers. You either need to use TLS, or change protocols to `Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http1AndHttp2` (although it will always use HTTP/1.1 because TLS is not available)

**Comment by herman1vdb** [comment]
I'm trying the same but within the scope of an Azure App Service.
>     option.ListenAnyIP(80, config =>
>     {
>         config.Protocols = Microsoft.AspNetCore.Server.Kestrel.Core.HttpProtocols.Http2;
>     });

I can't just use Http2 because Azure App Service thinks the app doesn't startup because of an error for the root path
`MapGet("\", ....` (see similar error: [Stackoverflow Http2ConnectionErrorException](https://stackoverflow.com/questions/56854434/microsoft-aspnetcore-server-kestrel-core-internal-http2-http2connectionerrorexce))

AppServices terminates the TLS see: [Detect Https Session](https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-linux#detect-https-session)

Therefore I really need Http1AndHttp2 without TLS (is this even possible?)

**Comment by JamesNK** [comment]
No.
