### ISSUE TITLE
Exclude gRPC headers from call context?

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#81]
re: https://github.com/grpc/grpc-dotnet/pull/73#discussion_r255155112

Investigate what Grpc.Core does with grpc specific headers and make Grpc.AspNetCore.Server follow.

**Comment by dhhoang** [comment]
Hi, I'm looking to contribute to this repo.
I spent sometime going through `Grpc.Core` and the C library code base. With regard to #73 the C lib does expose grpc-specific metadata (see https://github.com/grpc/grpc/blob/ff51441a29403c50495dc6ee3708e04ff088871d/include/grpc/impl/codegen/grpc_types.h#L497) and the server/client apps can query them. 

How they are handled depends on the metadata itself. For ex with deadline/timeout the client will cancel the request by sending an DEADLINE_EXCEEDED to the application (possibly a RST_STREAM to the server), while the server does not have any default behavior (see comments https://github.com/grpc/grpc/blob/master/src/core/ext/filters/deadline/deadline_filter.cc#L189 ).

Depending on what behavior we want there might be different ways to handle these headers but I think exposing them to applications is a good idea. That might also depend on whether or not `grpc-dotnet
` will have a dependency on `Grpc.Core`.

**Comment by JamesNK** [comment]
Actual cancellation and setting the right status is in this PR - https://github.com/grpc/grpc-dotnet/pull/84

A simple way to find out what headers ServerCallContext exposes gRPC specific headers is to run the native .NET server and test. I do know the client has a specific argument in the call options for setting a deadline that is separate from other headers.

**Comment by dhhoang** [comment]
Turns out that the way `Grpc.Core` deals with headers is a little more complicated. I tried running the native server and it looks like the default behavior is to maintain the headers, except for some.
`grpc-timeout` is not stored in the metadata collection but the deadline is exposed : https://github.com/grpc/grpc/blob/ff51441a29403c50495dc6ee3708e04ff088871d/include/grpc/impl/codegen/grpc_types.h#L506 
Some other headers have special handling by the framework. For example a request with `grpc-status` set to anything other than 0 will be considered an error: https://github.com/grpc/grpc/blob/ff51441a29403c50495dc6ee3708e04ff088871d/src/core/ext/transport/chttp2/transport/parsing.cc#L425 
Is that ok if I send an PR for this?

**Comment by JamesNK** [comment]
grpc-timeout is special cased on the client as well. CallOptions takes it as a seperate parameter to the headers collection.

Sure, send a PR. I think there is going to be a lot of small changes to get this project to response with the same HTTP messages as Grpc.Core.
