### ISSUE TITLE
Grpc Client - Interceptor - only created once (singleton)

### ISSUE THREAD

**Issue by rizi** [grpc/grpc-dotnet#842]
I've created an interceptor for gRPC clients like it's described here: https://docs.microsoft.com/en-us/aspnet/core/grpc/clientfactory?view=aspnetcore-3.1 and it's working fine.

However I want that the inceptor (in my sample below it's called MyClientInterceptor) is created for each request, at the moment it's created on the first call and all subsequent calls using the same instance of MyClientInterceptor.

I also registered MyClientIncepter in Unity 5 (I use Microsoft Unity as IOC) as transient, but that doesn't help because .AddInterceptor() adds the interceptor to a collection instead of resolving it for each request.

Is there some way I can archive this?
I want/need to do this because I have to resolve some other instances from the current ioc-container (the child container that's automatically created for each request).

I've registered the interceptor like this (there are also some overloads for interceptor but the beaviour is the same):

```
services
    .AddGrpcClient<Greeter.GreeterClient>(o =>
    {
        o.Address = new Uri("https://localhost:5001");
    })
    .AddInterceptor<MyClientInterceptor>();
```

br

**Comment by JamesNK** [comment]
Also register MyClientInterceptor as a singleton:

```cs
services.AddSingleton<MyClientInterceptor>();
```

**Comment by rizi** [comment]
> Also register MyClientInterceptor as a singleton:
> 
> ```cs
> services.AddSingleton<MyClientInterceptor>();
> ```

But I want exactly the opposite of a singleton, I want that MyClientIntercetor is created every time(transient). But it seems to register it transient has no effect, maybe I'm doing something wrong?

**Comment by JamesNK** [comment]
I see. I read your question wrong. I'll take a look.

**Comment by JamesNK** [comment]
Currently transient interceptors are not supported. We might be able to add support for them in a future version of the gRPC client factory.

**Comment by rizi** [comment]
> Currently transient interceptors are not supported. We might be able to add support for them in a future version of the gRPC client factory.

Thx for the fast response.

**Comment by gsmeets** [comment]
@JamesNK are singletons the only supported interceptor on the client? I'm trying to add a scoped interceptor, but that also doesn't seem to work.

I'm running into this issue porting my own NET Core 2.2 implementation to 3.1 now, removing as much of my own stuff as possible. It's a fairly common use case to want to piggy back some request based meta data from for instance an web request onto the grpc request.

**Comment by JamesNK** [comment]
> are singletons the only supported interceptor on the client?

Yes.

I'll see whether I can improve this in future versions.

**Comment by abe545** [comment]
Hi @JamesNK - just wanted to add Namely's upvote for making the interceptors scoped to individual requests. We use them for a few things that use information from the current request:
1. Forward additional headers that aren't handled by the default implementation
2. Automatically inject a service authorization token if not user initiated for specific endpoints
3. Emit metrics for problematic patterns (for instance, detect if an RPC is happening in the context of an open DB transaction)
4. Distributed tracing

Most of the above are entirely possible if the interceptors are singletons if the service is running in the context of asp .net (whether grpc or mvc) using the `IHttpContextAccessor`. However, we have applications that are based on kafka handlers, and we still want to support things like forwarding request headers from the kafka message. So we'd essentially have to implement the same pattern for accessing the current request, instead of what we do now - inject the current request information using DI inside a request scope. This would be a fair amount of code to change for us, and I'd like to avoid doing so if at all possible.

I've been able to work around this by registering my own implementation of the `GrpcClientFactory` as transient, while creating and holding a reference to the `GrpcChannel` in a singleton `GrpcChannelFactory`. We've been hesitant to widely deploy this, as we're not 100% sure if we're introducing some subtle bug with the channel; but our c-based implementation just kept the channels as singletons, so I'm fairly confident it will not be worse.

**Comment by FelixSFD** [comment]
@abe545 Did your implementation of `GrpcClientFactory` work? If it did, could you please share your `GrpcClientFactory` with us?
I have a similar requirement, where I need to forward some custom headers.

**Comment by abe545** [comment]
> @abe545 Did your implementation of `GrpcClientFactory` work? If it did, could you please share your `GrpcClientFactory` with us?
> I have a similar requirement, where I need to forward some custom headers.

It did work, and I'd be happy to: https://gist.github.com/abe545/c8b88fbdbd2d89ece5269a33fa8cae51
This doesn't include the client registration because it is written using a lot of other proprietary code that would be hard to tease out quickly, but hopefully this can help you get started.

**Comment by FelixSFD** [comment]
Thanks for your help! :-)
Unfortunately, I ran into DNS-issues when using your solution within Docker containers. Looks like the channel has been opened before the other services were online and therefore the internal DNS-resolver did not recognize the names.

I ended up creating a subclass of `GrpcClientFactoryOptions` which adds the interceptors to `GrpcClientFactoryOptions.Interceptors`. To register the clients, I created a static method with a type parameter:

```csharp
/// Helper-class to register gRPC-clients
public class RegisterGrpcClient
{
  /// <summary>
  /// Registers a client with an URL
  /// </summary>
  /// <typeparam name="T">Type of gRPC-client</typeparam>
  /// <param name="services"></param>
  /// <param name="connectionString">URL to the server</param>
  public static void Register<T>(IServiceCollection services, string connectionString) where T : class
  {
    services.AddScoped<T>((provider) =>
    {
      GrpcClientFactoryOptions opt = provider.GetRequiredService<GrpcClientFactoryOptions>();
      var channel = GrpcChannel.ForAddress(connectionString);
      CallInvoker httpClientCallInvoker = channel.CreateCallInvoker();
      var resolvedCallInvoker = opt.Interceptors.Count == 0
        ? httpClientCallInvoker
        : httpClientCallInvoker.Intercept(opt.Interceptors.ToArray());
      ObjectFactory objectFactory = ActivatorUtilities.CreateFactory(typeof(T), new Type[] { typeof(CallInvoker), });
      return (T)objectFactory.Invoke(provider, new object[] { resolvedCallInvoker });
    });
  }
}
```
I was able to reuse some of your code for this.


This code is not deployed yet, so I can't guarantee that it actually works without any issues. But it works on my computer ;-)

**Comment by amsga89** [comment]
builder.Services
    .AddGrpcClient<Greeter.GreeterClient>(o =>
    {
        o.Address = new Uri("https://localhost:5001");
    })
    .AddInterceptor<LoggingInterceptor>(**InterceptorScope.Client**);
