### ISSUE TITLE
Multiple GRPC Clients in .net  

### ISSUE THREAD

**Issue by MhdAna** [grpc/grpc-dotnet#898]
I have some questions regarding this topic multiple clients : 
1- Can I have multiple clients on the client endpoint talking to a single service?
2- If it is possible , Can I use only one channel shared between them (Assumption : I would expect that the clients are not going to use the channel in the same time).
3- If it is possible how do I achieve multiple clients for a given service on a client endpoint?
    I researched about that : it says it is possible but i must have multiple stubs generated either from one single channel or from multiple channels, 
My Question : If it is correct how do i generate multiple Stubs???? 
                       It would be helpful to give me an code Example. 

4- How the Server will be able to distinguish those multiple clients, if we are using the one channel for the communication?
 
Thanks for Any Help

**Comment by chwarr** [comment]
> Can I have multiple clients on the client endpoint talking to a single service?

Yes. You'll need to make sure that your server-side implementation is asynchronous so that it can actually service multiple clients concurrently.

> If it is possible , Can I use only one channel shared between them (Assumption : I would expect that the clients are not going to use the channel in the same time).

Yes, you can share a channel among multiple clients. They can even use the channel at the same time. (The channel will handle any mutual exclusion needed.)

> If it is possible how do I achieve multiple clients for a given service on a client endpoint?
I researched about that : it says it is possible but i must have multiple stubs generated either from one single channel or from multiple channels,
> My Question : If it is correct how do i generate multiple Stubs????

You don't need to _generate_ multiple stubs, You need to _instantiate_ multiple instances of the same stub.

```csharp
var channel = GrpcChannel.ForAddress("https://localhost:5001");
var client1 = new Mailer.MailerClient(channel);
var client2 = new Mailer.MailerClient(channel);
var client3 = new Mailer.MailerClient(channel);
```

> How the Server will be able to distinguish those multiple clients, if we are using the one channel for the communication?

What's the higher level problem you're trying to solve? There's likely a better way than client identity to solve it.

**Comment by JamesNK** [comment]
I believe this questions are all answered in the documentation: https://docs.microsoft.com/en-us/aspnet/core/grpc/client?view=aspnetcore-3.1

**Comment by MhdAna** [comment]
Thanks very much for your answers,
actually it seems that I have to use ASP.Net Core project,

**Comment by JamesNK** [comment]
grpc-dotnet only supports netcoreapp3.0 and later.
