### ISSUE TITLE
How to enable support for optional?

### ISSUE THREAD

**Issue by JohnGalt1717** [grpc/grpc-dotnet#977]
How does one turn on support for the optional keyword in proto3 (latest version)?  Given how great nullable types are, it would be really wonderful if this turned on the entire pipeline and just worked, but it doesn't seem to as it errors and tells me that I need --experimental_allow_proto3_optional but I can't find out how to pass that in csproj etc.

**Comment by JunTaoLuo** [comment]
I think the answer in https://github.com/dotnet/AspNetCore.Docs/issues/19164 covers this issue. Given that I closed that issue, I'll continue the conversation here. 

In terms of the unrecognized option, it seems like the protoc compiler is out of date. Which version of the grpc/protobuf libraries are you using? From what I can tell from https://github.com/protocolbuffers/protobuf/blob/master/docs/field_presence.md#protoc-invocation Google.Protobuf 3.1.12 or newer is needed to support this flag. And I see at least Grpc.Tools 2.30.0-pre1 would be new enough to support it. Can you update your references to the latest and let me know if that works? Otherwise there might be something wrong with the protoc compiler included in Grpc.Tools and we'll need to file an issue to https://github.com/grpc/grpc

**Comment by JunTaoLuo** [comment]
There hasn't been any response in the past 7 days so we are closing this issue. Please reopen or open a new issue if you you would like to discuss further.

**Comment by JohnGalt1717** [comment]
I have the following using Grpc.Tools 2.30.0 which was released in the last few days:

<Protobuf Include="../../Account/Account.Proto/**/*.proto" GrpcServices="Both" ProtoRoot="./../.." GrpcOutputOptions="--experimental_allow_proto3_optional" />

I sitll get: "This file contains proto3 optional fields, but --experimental_allow_proto3_optional was not set."

What am I doing wrong?

**Comment by JamesNK** [comment]
I'm not familiar with proto3 and optional. You should ask Grpc.Tools specific questions at grpc/grpc. Grpc.Tools is maintained there.
